# Generated by Django 4.1 on 2023-06-20 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CalorieGoal",
            fields=[
                (
                    "calorie_goal_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("target_calories", models.IntegerField()),
                ("begin_date", models.DateField()),
                ("end_date", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DailyMacroGoal",
            fields=[
                ("daily_macro_id", models.AutoField(primary_key=True, serialize=False)),
                ("protein_goal", models.IntegerField()),
                ("carbohydrate_goal", models.IntegerField()),
                ("fat_goal", models.IntegerField()),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                ("exercise_id", models.AutoField(primary_key=True, serialize=False)),
                ("exercise_type", models.CharField(max_length=50)),
                ("calories_burned_per_minute", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                ("food_id", models.AutoField(primary_key=True, serialize=False)),
                ("food_name", models.CharField(max_length=50)),
                ("calories_per_serving", models.IntegerField()),
                ("protein_grams", models.IntegerField()),
                ("carbohydrates_grams", models.IntegerField()),
                ("fat_grams", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                ("meal_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meals",
                        to="calorie_counter.food",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                ("member_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("e_mail", models.EmailField(max_length=50)),
                ("height", models.IntegerField(help_text="Height in inches")),
                ("weight", models.IntegerField(help_text="Weight in pounds")),
                ("age", models.IntegerField(help_text="Age in years")),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        help_text="Male = M, Female = F",
                        max_length=1,
                    ),
                ),
                ("date_joined", models.DateField()),
                (
                    "calorie_goal",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="calorie_counter.caloriegoal",
                    ),
                ),
                (
                    "daily_macro_goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="calorie_counter.dailymacrogoal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MealLog",
            fields=[
                ("meal_log_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meal_logs",
                        to="calorie_counter.meal",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meal_logs",
                        to="calorie_counter.member",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExerciseLog",
            fields=[
                (
                    "exercise_log_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                ("duration", models.TimeField()),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exercise_logs",
                        to="calorie_counter.exercise",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exercise_logs",
                        to="calorie_counter.member",
                    ),
                ),
            ],
        ),
    ]
