# Generated by Django 4.1 on 2023-06-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calorie_counter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="disambiguator",
            field=models.CharField(blank=True, default="", max_length=45),
        ),
    ]
