# Generated by Django 4.1 on 2023-06-16 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calorie_counter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="calorie_goal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="members",
                to="calorie_counter.caloriegoal",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="daily_macro_goal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="members",
                to="calorie_counter.dailymacrogoal",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="date_joined",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="exercise_log",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="members",
                to="calorie_counter.exerciselog",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Height in feet and inches",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="meal_log",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="members",
                to="calorie_counter.meallog",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="sex",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Weight in pounds",
                max_digits=6,
                null=True,
            ),
        ),
    ]
