# Generated by Django 4.1 on 2023-06-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calorie_counter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member", name="age", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="member", name="e_mail", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="member",
            name="height",
            field=models.IntegerField(help_text="Height in feet and inches"),
        ),
        migrations.AlterField(
            model_name="member", name="sex", field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name="member",
            name="weight",
            field=models.IntegerField(help_text="Weight in pounds"),
        ),
    ]
