# Generated by Django 4.1 on 2023-06-16 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calorie_counter", "0002_alter_member_age_alter_member_calorie_goal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member", name="age", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="member",
            name="calorie_goal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="members",
                to="calorie_counter.caloriegoal",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="daily_macro_goal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="members",
                to="calorie_counter.dailymacrogoal",
            ),
        ),
        migrations.AlterField(
            model_name="member", name="date_joined", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="member",
            name="exercise_log",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="members",
                to="calorie_counter.exerciselog",
            ),
        ),
        migrations.AlterField(
            model_name="member", name="height", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="member",
            name="meal_log",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="members",
                to="calorie_counter.meallog",
            ),
        ),
        migrations.AlterField(
            model_name="member", name="sex", field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name="member", name="weight", field=models.IntegerField(),
        ),
    ]
