# Generated by Django 4.1 on 2023-07-15 16:37
from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations

MEMBERS = [
    {
        "first_name": "James",
        "last_name": "Roth",
        "e_mail": "pricemichael@example.org",
        "height": 72,
        "weight": 117,
        "age": 38,
        "sex": "F",
        "date_joined": "2022-10-19",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Elizabeth",
        "last_name": "Martin",
        "e_mail": "justin40@example.com",
        "height": 68,
        "weight": 122,
        "age": 46,
        "sex": "F",
        "date_joined": "2022-08-20",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Vicki",
        "last_name": "Le",
        "e_mail": "angela38@example.org",
        "height": 71,
        "weight": 109,
        "age": 81,
        "sex": "F",
        "date_joined": "2022-09-10",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Jennifer",
        "last_name": "Frazier",
        "e_mail": "bushmatthew@example.org",
        "height": 72,
        "weight": 151,
        "age": 68,
        "sex": "F",
        "date_joined": "2023-04-26",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Gregory",
        "last_name": "Kelley",
        "e_mail": "kevin37@example.net",
        "height": 61,
        "weight": 238,
        "age": 47,
        "sex": "M",
        "date_joined": "2023-05-31",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Scott",
        "last_name": "Terry",
        "e_mail": "jennifersanchez@example.com",
        "height": 65,
        "weight": 189,
        "age": 26,
        "sex": "M",
        "date_joined": "2023-02-06",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Jay",
        "last_name": "Gordon",
        "e_mail": "shanetaylor@example.net",
        "height": 61,
        "weight": 158,
        "age": 86,
        "sex": "M",
        "date_joined": "2022-09-27",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Michael",
        "last_name": "Fleming",
        "e_mail": "olivia88@example.org",
        "height": 79,
        "weight": 235,
        "age": 52,
        "sex": "M",
        "date_joined": "2023-04-19",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Vanessa",
        "last_name": "Diaz",
        "e_mail": "ejohnson@example.com",
        "height": 73,
        "weight": 214,
        "age": 48,
        "sex": "F",
        "date_joined": "2023-04-27",
        "disambiguator": "Testing"
    },
    {
        "first_name": "William",
        "last_name": "Strickland",
        "e_mail": "ostafford@example.net",
        "height": 61,
        "weight": 238,
        "age": 38,
        "sex": "F",
        "date_joined": "2023-02-09",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Courtney",
        "last_name": "Archer",
        "e_mail": "butlerkristina@example.com",
        "height": 65,
        "weight": 146,
        "age": 50,
        "sex": "M",
        "date_joined": "2023-05-10",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Kimberly",
        "last_name": "Garza",
        "e_mail": "lori51@example.com",
        "height": 73,
        "weight": 124,
        "age": 58,
        "sex": "M",
        "date_joined": "2023-02-28",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Devin",
        "last_name": "Sutton",
        "e_mail": "larry85@example.com",
        "height": 76,
        "weight": 214,
        "age": 57,
        "sex": "F",
        "date_joined": "2023-03-18",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Douglas",
        "last_name": "Mason",
        "e_mail": "scottjonathan@example.net",
        "height": 63,
        "weight": 207,
        "age": 23,
        "sex": "M",
        "date_joined": "2023-07-08",
        "disambiguator": "Testing"
    },
    {
        "first_name": "James",
        "last_name": "Gonzalez",
        "e_mail": "ryanreyes@example.org",
        "height": 73,
        "weight": 181,
        "age": 73,
        "sex": "M",
        "date_joined": "2022-09-09",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Annette",
        "last_name": "Rogers",
        "e_mail": "moraleshannah@example.com",
        "height": 69,
        "weight": 237,
        "age": 85,
        "sex": "M",
        "date_joined": "2022-10-29",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Ashley",
        "last_name": "Freeman",
        "e_mail": "zhopkins@example.com",
        "height": 61,
        "weight": 185,
        "age": 75,
        "sex": "F",
        "date_joined": "2023-07-03",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Lindsey",
        "last_name": "Moreno",
        "e_mail": "kleinmichele@example.org",
        "height": 60,
        "weight": 204,
        "age": 84,
        "sex": "M",
        "date_joined": "2023-07-06",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Jeffrey",
        "last_name": "Moon",
        "e_mail": "taylornatasha@example.net",
        "height": 67,
        "weight": 205,
        "age": 52,
        "sex": "M",
        "date_joined": "2023-03-05",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Christopher",
        "last_name": "Richardson",
        "e_mail": "cfisher@example.org",
        "height": 70,
        "weight": 112,
        "age": 63,
        "sex": "M",
        "date_joined": "2023-01-03",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Charles",
        "last_name": "Bauer",
        "e_mail": "michaelnewton@example.net",
        "height": 66,
        "weight": 144,
        "age": 76,
        "sex": "M",
        "date_joined": "2022-07-19",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Jaclyn",
        "last_name": "Barnes",
        "e_mail": "ryan25@example.com",
        "height": 71,
        "weight": 168,
        "age": 25,
        "sex": "F",
        "date_joined": "2022-12-20",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Krystal",
        "last_name": "Romero",
        "e_mail": "santiagochelsea@example.com",
        "height": 72,
        "weight": 185,
        "age": 36,
        "sex": "M",
        "date_joined": "2022-11-05",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Brenda",
        "last_name": "Hall",
        "e_mail": "qarnold@example.net",
        "height": 80,
        "weight": 144,
        "age": 19,
        "sex": "F",
        "date_joined": "2023-06-01",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Calvin",
        "last_name": "Brown",
        "e_mail": "sethhatfield@example.org",
        "height": 76,
        "weight": 103,
        "age": 87,
        "sex": "F",
        "date_joined": "2023-03-18",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Kathy",
        "last_name": "Ho",
        "e_mail": "christopher14@example.com",
        "height": 65,
        "weight": 130,
        "age": 51,
        "sex": "F",
        "date_joined": "2022-11-27",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Susan",
        "last_name": "Reed",
        "e_mail": "gonzalezbruce@example.net",
        "height": 72,
        "weight": 163,
        "age": 68,
        "sex": "M",
        "date_joined": "2022-11-18",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Samantha",
        "last_name": "Davidson",
        "e_mail": "bellmorgan@example.net",
        "height": 72,
        "weight": 142,
        "age": 19,
        "sex": "M",
        "date_joined": "2023-06-05",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Steven",
        "last_name": "Moody",
        "e_mail": "higginsross@example.net",
        "height": 69,
        "weight": 102,
        "age": 76,
        "sex": "M",
        "date_joined": "2023-06-13",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Kevin",
        "last_name": "Brooks",
        "e_mail": "smithronald@example.org",
        "height": 79,
        "weight": 136,
        "age": 86,
        "sex": "F",
        "date_joined": "2023-06-30",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Sean",
        "last_name": "Mclaughlin",
        "e_mail": "stacyadams@example.org",
        "height": 70,
        "weight": 105,
        "age": 26,
        "sex": "M",
        "date_joined": "2023-05-10",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Katherine",
        "last_name": "Harris",
        "e_mail": "glewis@example.com",
        "height": 78,
        "weight": 206,
        "age": 89,
        "sex": "F",
        "date_joined": "2022-12-13",
        "disambiguator": "Testing"
    },
    {
        "first_name": "David",
        "last_name": "Silva",
        "e_mail": "campbellvictoria@example.org",
        "height": 62,
        "weight": 111,
        "age": 62,
        "sex": "F",
        "date_joined": "2022-08-08",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Christina",
        "last_name": "Perkins",
        "e_mail": "logan13@example.com",
        "height": 64,
        "weight": 234,
        "age": 81,
        "sex": "F",
        "date_joined": "2022-12-15",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Zoe",
        "last_name": "May",
        "e_mail": "dpeters@example.org",
        "height": 75,
        "weight": 241,
        "age": 89,
        "sex": "F",
        "date_joined": "2023-03-11",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Lauren",
        "last_name": "Rasmussen",
        "e_mail": "richard90@example.net",
        "height": 68,
        "weight": 224,
        "age": 31,
        "sex": "M",
        "date_joined": "2022-09-16",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Joseph",
        "last_name": "Smith",
        "e_mail": "bradleyhubbard@example.org",
        "height": 76,
        "weight": 200,
        "age": 85,
        "sex": "M",
        "date_joined": "2022-10-29",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Erica",
        "last_name": "Everett",
        "e_mail": "gonzalezlauren@example.com",
        "height": 64,
        "weight": 200,
        "age": 36,
        "sex": "M",
        "date_joined": "2022-07-31",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Jonathan",
        "last_name": "Barnes",
        "e_mail": "edwin47@example.org",
        "height": 78,
        "weight": 231,
        "age": 75,
        "sex": "M",
        "date_joined": "2023-05-13",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Karen",
        "last_name": "Page",
        "e_mail": "sabrinasawyer@example.net",
        "height": 61,
        "weight": 160,
        "age": 75,
        "sex": "F",
        "date_joined": "2023-03-03",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Annette",
        "last_name": "Daniel",
        "e_mail": "sergio27@example.net",
        "height": 67,
        "weight": 183,
        "age": 66,
        "sex": "F",
        "date_joined": "2023-06-30",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Victoria",
        "last_name": "Williams",
        "e_mail": "tyler00@example.com",
        "height": 60,
        "weight": 202,
        "age": 34,
        "sex": "F",
        "date_joined": "2023-01-04",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Michael",
        "last_name": "Powers",
        "e_mail": "davidramirez@example.com",
        "height": 64,
        "weight": 165,
        "age": 40,
        "sex": "F",
        "date_joined": "2022-11-04",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Lisa",
        "last_name": "Ingram",
        "e_mail": "aliciagalvan@example.com",
        "height": 69,
        "weight": 208,
        "age": 27,
        "sex": "F",
        "date_joined": "2023-02-02",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Deborah",
        "last_name": "Mckay",
        "e_mail": "jasonjones@example.org",
        "height": 62,
        "weight": 247,
        "age": 84,
        "sex": "M",
        "date_joined": "2023-04-16",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Regina",
        "last_name": "Baker",
        "e_mail": "frederickbanks@example.net",
        "height": 78,
        "weight": 194,
        "age": 38,
        "sex": "F",
        "date_joined": "2022-12-26",
        "disambiguator": "Testing"
    },
    {
        "first_name": "David",
        "last_name": "Lynch",
        "e_mail": "garzajulie@example.org",
        "height": 79,
        "weight": 213,
        "age": 25,
        "sex": "F",
        "date_joined": "2022-12-07",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Frank",
        "last_name": "Stewart",
        "e_mail": "travisashley@example.org",
        "height": 78,
        "weight": 193,
        "age": 72,
        "sex": "M",
        "date_joined": "2023-04-07",
        "disambiguator": "Testing"
    },
    {
        "first_name": "Hailey",
        "last_name": "Blankenship",
        "e_mail": "lori96@example.com",
        "height": 66,
        "weight": 140,
        "age": 71,
        "sex": "F",
        "date_joined": "2022-07-27",
        "disambiguator": "Testing"
    },
    {
        "first_name": "William",
        "last_name": "Collins",
        "e_mail": "diana41@example.com",
        "height": 79,
        "weight": 221,
        "age": 51,
        "sex": "M",
        "date_joined": "2022-12-10",
        "disambiguator": "Testing"
    }
]


def add_member_data(apps, schema_editor):
    member_class = apps.get_model('calorie_counter', 'Member')
    for member in MEMBERS:
        try:
            duplicate_object = member_class.objects.get(
                first_name=member['first_name'],
                last_name=member['last_name'],
                e_mail=member['e_mail'],
                height=member['height'],
                weight=member['weight'],
                age=member['age'],
                sex=member['sex'],
                date_joined=member['date_joined'],
                disambiguator=member['disambiguator']
            )
            print('Duplicate member entry not added to member table:', member['first_name'], member['last_name'])
        except ObjectDoesNotExist:
            member_object = member_class.objects.create(
                first_name=member['first_name'],
                last_name=member['last_name'],
                e_mail=member['e_mail'],
                height=member['height'],
                weight=member['weight'],
                age=member['age'],
                sex=member['sex'],
                date_joined=member['date_joined'],
                disambiguator=member['disambiguator']
            )


def remove_member_data(apps, schema_editor):
    member_class = apps.get_model('calorie_counter', 'Member')
    for member in MEMBERS:
        member_object = member_class.objects.get(
            first_name=member['first_name'],
            last_name=member['last_name'],
            e_mail=member['e_mail'],
            height=member['height'],
            weight=member['weight'],
            age=member['age'],
            sex=member['sex'],
            date_joined=member['date_joined'],
            disambiguator=member['disambiguator']
        )
        member_object.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("calorie_counter", "0002_member_disambiguator"),
    ]

    operations = [migrations.RunPython(
            add_member_data,
            remove_member_data)]
