# Generated by Django 4.1 on 2023-07-16 16:04
from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations

FOODS = [

        {
            "name": "Nutella",
            "calories_per_serving": 393,
            "protein_grams": 59,
            "carbohydrates_grams": 14,
            "fat_grams": 37
        },
        {
            "name": "Prince Chocolat biscuits",
            "calories_per_serving": 388,
            "protein_grams": 68,
            "carbohydrates_grams": 17,
            "fat_grams": 84
        },
        {
            "name": "Coca Cola Zero",
            "calories_per_serving": 232,
            "protein_grams": 72,
            "carbohydrates_grams": 23,
            "fat_grams": 27
        },
        {
            "name": "Muesli Raisin, Figue, Abricot",
            "calories_per_serving": 460,
            "protein_grams": 4,
            "carbohydrates_grams": 15,
            "fat_grams": 10
        },
        {
            "name": "pain au lait",
            "calories_per_serving": 591,
            "protein_grams": 83,
            "carbohydrates_grams": 35,
            "fat_grams": 28
        },
        {
            "name": "Oreo",
            "calories_per_serving": 273,
            "protein_grams": 20,
            "carbohydrates_grams": 63,
            "fat_grams": 64
        },
        {
            "name": "Le Beurre Tendre Doux",
            "calories_per_serving": 112,
            "protein_grams": 25,
            "carbohydrates_grams": 58,
            "fat_grams": 52
        },
        {
            "name": "Snickers",
            "calories_per_serving": 564,
            "protein_grams": 40,
            "carbohydrates_grams": 41,
            "fat_grams": 22
        },
        {
            "name": "Tomato Ketchup BIO",
            "calories_per_serving": 598,
            "protein_grams": 96,
            "carbohydrates_grams": 68,
            "fat_grams": 57
        },
        {
            "name": "Spaghetti n.5",
            "calories_per_serving": 85,
            "protein_grams": 63,
            "carbohydrates_grams": 21,
            "fat_grams": 78
        },
        {
            "name": "Copos de avena",
            "calories_per_serving": 244,
            "protein_grams": 98,
            "carbohydrates_grams": 25,
            "fat_grams": 27
        },
        {
            "name": "Tomaten Fruchtfleisch",
            "calories_per_serving": 415,
            "protein_grams": 84,
            "carbohydrates_grams": 34,
            "fat_grams": 37
        },
        {
            "name": "Chocolate",
            "calories_per_serving": 269,
            "protein_grams": 18,
            "carbohydrates_grams": 50,
            "fat_grams": 11
        },
        {
            "name": "Lipton Ice Tea ",
            "calories_per_serving": 156,
            "protein_grams": 88,
            "carbohydrates_grams": 49,
            "fat_grams": 32
        },
        {
            "name": "Nature",
            "calories_per_serving": 204,
            "protein_grams": 10,
            "carbohydrates_grams": 48,
            "fat_grams": 22
        },
        {
            "name": "Caprice des dieux",
            "calories_per_serving": 427,
            "protein_grams": 11,
            "carbohydrates_grams": 76,
            "fat_grams": 47
        },

        {
            "name": "Bananas",
            "calories_per_serving": 207,
            "protein_grams": 68,
            "carbohydrates_grams": 19,
            "fat_grams": 67
        },
        {
            "name": "Prince petit dej",
            "calories_per_serving": 172,
            "protein_grams": 20,
            "carbohydrates_grams": 4,
            "fat_grams": 63
        },
        {
            "name": "collezione linguine",
            "calories_per_serving": 107,
            "protein_grams": 23,
            "carbohydrates_grams": 1,
            "fat_grams": 4
        },
        {
            "name": "Thunfisch",
            "calories_per_serving": 476,
            "protein_grams": 83,
            "carbohydrates_grams": 16,
            "fat_grams": 59
        },
        {
            "name": "Pain de mie longue conservation",
            "calories_per_serving": 556,
            "protein_grams": 66,
            "carbohydrates_grams": 60,
            "fat_grams": 45
        },
        {
            "name": "Couscous sachet cuisson",
            "calories_per_serving": 133,
            "protein_grams": 26,
            "carbohydrates_grams": 55,
            "fat_grams": 75
        },
        {
            "name": "Flocons d'avoine 4 graines et raisins",
            "calories_per_serving": 549,
            "protein_grams": 1,
            "carbohydrates_grams": 75,
            "fat_grams": 93
        },
        {
            "name": "Big Mac",
            "calories_per_serving": 384,
            "protein_grams": 16,
            "carbohydrates_grams": 14,
            "fat_grams": 70
        },
        {
            "name": "Zartbitterschokolade",
            "calories_per_serving": 586,
            "protein_grams": 23,
            "carbohydrates_grams": 29,
            "fat_grams": 52
        },
        {
            "name": "COFFEE MATE AVELLANA",
            "calories_per_serving": 456,
            "protein_grams": 13,
            "carbohydrates_grams": 18,
            "fat_grams": 28
        },
        {
            "name": "Bebida de avena",
            "calories_per_serving": 199,
            "protein_grams": 28,
            "carbohydrates_grams": 16,
            "fat_grams": 91
        },
        {
            "name": "Nutella",
            "calories_per_serving": 199,
            "protein_grams": 44,
            "carbohydrates_grams": 89,
            "fat_grams": 53
        },
        {
            "name": "Ecoleaf Jumbo Roll Kitchen Tow",
            "calories_per_serving": 241,
            "protein_grams": 48,
            "carbohydrates_grams": 40,
            "fat_grams": 94
        },

        {
            "name": "Tunisian extra virgin olive oil",
            "calories_per_serving": 94,
            "protein_grams": 95,
            "carbohydrates_grams": 52,
            "fat_grams": 42
        },
        {
            "name": "Capellini n.1",
            "calories_per_serving": 286,
            "protein_grams": 25,
            "carbohydrates_grams": 4,
            "fat_grams": 98
        },
        {
            "name": "Raspberry fruit spread, raspberry",
            "calories_per_serving": 250,
            "protein_grams": 48,
            "carbohydrates_grams": 52,
            "fat_grams": 70
        },
        {
            "name": "Energie 1 Protein Shake",
            "calories_per_serving": 526,
            "protein_grams": 67,
            "carbohydrates_grams": 87,
            "fat_grams": 84
        },
        {
            "name": "Wraps Multigrains",
            "calories_per_serving": 480,
            "protein_grams": 31,
            "carbohydrates_grams": 50,
            "fat_grams": 64
        },
        {
            "name": "Mamas Babydream Stillsaft",
            "calories_per_serving": 458,
            "protein_grams": 63,
            "carbohydrates_grams": 95,
            "fat_grams": 27
        },
        {
            "name": "pasta mix",
            "calories_per_serving": 511,
            "protein_grams": 3,
            "carbohydrates_grams": 87,
            "fat_grams": 98
        },
        {
            "name": "Bio smoothie",
            "calories_per_serving": 476,
            "protein_grams": 34,
            "carbohydrates_grams": 15,
            "fat_grams": 44
        },
        {
            "name": "Kola Granulada Tarrito Rojo",
            "calories_per_serving": 158,
            "protein_grams": 17,
            "carbohydrates_grams": 3,
            "fat_grams": 76
        },
        {
            "name": "hairtamin",
            "calories_per_serving": 413,
            "protein_grams": 4,
            "carbohydrates_grams": 33,
            "fat_grams": 12
        },
        {
            "name": "Diet sweet",
            "calories_per_serving": 241,
            "protein_grams": 56,
            "carbohydrates_grams": 17,
            "fat_grams": 80
        },
        {
            "name": "Chocolate bars",
            "calories_per_serving": 470,
            "protein_grams": 12,
            "carbohydrates_grams": 84,
            "fat_grams": 82
        },
        {
            "name": "Ekologisk r\u00f6d quinoa",
            "calories_per_serving": 521,
            "protein_grams": 65,
            "carbohydrates_grams": 38,
            "fat_grams": 42
        },
        {
            "name": "Pan Cero Azucar",
            "calories_per_serving": 316,
            "protein_grams": 50,
            "carbohydrates_grams": 70,
            "fat_grams": 7
        },
        {
            "name": "Pan 12 cereales y semillas",
            "calories_per_serving": 586,
            "protein_grams": 70,
            "carbohydrates_grams": 61,
            "fat_grams": 53
        },
        {
            "name": "Redbull",
            "calories_per_serving": 89,
            "protein_grams": 18,
            "carbohydrates_grams": 63,
            "fat_grams": 96
        },
        {
            "name": "Huile d'olive vierge extra",
            "calories_per_serving": 280,
            "protein_grams": 5,
            "carbohydrates_grams": 39,
            "fat_grams": 79
        },
        {
            "name": "Hi Goat - Goat's Milk Powder",
            "calories_per_serving": 81,
            "protein_grams": 51,
            "carbohydrates_grams": 31,
            "fat_grams": 37
        },
        {
            "name": "mayonnaise",
            "calories_per_serving": 303,
            "protein_grams": 44,
            "carbohydrates_grams": 89,
            "fat_grams": 70
        },
        {
            "name": "Roasted Cashews & Peanuts",
            "calories_per_serving": 93,
            "protein_grams": 58,
            "carbohydrates_grams": 10,
            "fat_grams": 29
        },
        {
            "name": "Ratatouille",
            "calories_per_serving": 56,
            "protein_grams": 46,
            "carbohydrates_grams": 98,
            "fat_grams": 96
        },
        {
            "name": "Monster pacific punch",
            "calories_per_serving": 366,
            "protein_grams": 66,
            "carbohydrates_grams": 55,
            "fat_grams": 45
        },
        {
            "name": "Tomatenmark",
            "calories_per_serving": 153,
            "protein_grams": 67,
            "carbohydrates_grams": 55,
            "fat_grams": 22
        },
        {
            "name": "NESTLE LION",
            "calories_per_serving": 483,
            "protein_grams": 24,
            "carbohydrates_grams": 7,
            "fat_grams": 87
        },
        {
            "name": "Oreo Original",
            "calories_per_serving": 319,
            "protein_grams": 2,
            "carbohydrates_grams": 29,
            "fat_grams": 76
        },
        {
            "name": "Fusilli Pasta, Whole Wheat",
            "calories_per_serving": 411,
            "protein_grams": 83,
            "carbohydrates_grams": 86,
            "fat_grams": 61
        },
        {
            "name": "Cioccolato al latte",
            "calories_per_serving": 156,
            "protein_grams": 46,
            "carbohydrates_grams": 8,
            "fat_grams": 59
        },
        {
            "name": "Brunch Paprika & Peperoni",
            "calories_per_serving": 297,
            "protein_grams": 5,
            "carbohydrates_grams": 61,
            "fat_grams": 52
        },
        {
            "name": "Polapezzi",
            "calories_per_serving": 440,
            "protein_grams": 53,
            "carbohydrates_grams": 89,
            "fat_grams": 58
        },
        {
            "name": "KONO DIO DA",
            "calories_per_serving": 415,
            "protein_grams": 52,
            "carbohydrates_grams": 50,
            "fat_grams": 43
        },
        {
            "name": "Kekse Jaffa Cake Soft-Biscuit",
            "calories_per_serving": 381,
            "protein_grams": 73,
            "carbohydrates_grams": 3,
            "fat_grams": 96
        },
        {
            "name": "Le Fruit - Orange sans pulpe",
            "calories_per_serving": 244,
            "protein_grams": 35,
            "carbohydrates_grams": 94,
            "fat_grams": 71
        },
        {
            "name": "Gervais le petit suisse",
            "calories_per_serving": 62,
            "protein_grams": 8,
            "carbohydrates_grams": 28,
            "fat_grams": 73
        },
        {
            "name": "Reese's Peanut Butter Cups std",
            "calories_per_serving": 561,
            "protein_grams": 66,
            "carbohydrates_grams": 15,
            "fat_grams": 74
        },
        {
            "name": "Pizza Margherita - p\u00e2te fine",
            "calories_per_serving": 438,
            "protein_grams": 92,
            "carbohydrates_grams": 98,
            "fat_grams": 1
        },
        {
            "name": "L'Originale - Farine de bl\u00e9 fluide T45",
            "calories_per_serving": 172,
            "protein_grams": 35,
            "carbohydrates_grams": 81,
            "fat_grams": 59
        },
        {
            "name": "Ravioli V\u00e9g\u00e9tariens",
            "calories_per_serving": 208,
            "protein_grams": 17,
            "carbohydrates_grams": 18,
            "fat_grams": 96
        },
        {
            "name": "Mayonnaise",
            "calories_per_serving": 440,
            "protein_grams": 8,
            "carbohydrates_grams": 1,
            "fat_grams": 100
        },
        {
            "name": "Cocktail nuts",
            "calories_per_serving": 311,
            "protein_grams": 17,
            "carbohydrates_grams": 26,
            "fat_grams": 60
        },
        {
            "name": "Huile d'olive",
            "calories_per_serving": 462,
            "protein_grams": 44,
            "carbohydrates_grams": 59,
            "fat_grams": 30
        },
        {
            "name": "Jogurt Bifidus Nature",
            "calories_per_serving": 71,
            "protein_grams": 97,
            "carbohydrates_grams": 57,
            "fat_grams": 70
        },
        {
            "name": "Cirio Diced Tomatoes",
            "calories_per_serving": 90,
            "protein_grams": 72,
            "carbohydrates_grams": 33,
            "fat_grams": 75
        },
        {
            "name": "Mogu mogu",
            "calories_per_serving": 492,
            "protein_grams": 28,
            "carbohydrates_grams": 83,
            "fat_grams": 13
        },
        {
            "name": "Doritos Nachos",
            "calories_per_serving": 297,
            "protein_grams": 100,
            "carbohydrates_grams": 57,
            "fat_grams": 72
        },
        {
            "name": "Coca-Cola",
            "calories_per_serving": 314,
            "protein_grams": 56,
            "carbohydrates_grams": 6,
            "fat_grams": 64
        },
        {
            "name": "Kokosmilch",
            "calories_per_serving": 193,
            "protein_grams": 52,
            "carbohydrates_grams": 68,
            "fat_grams": 87
        },
        {
            "name": "Schoko M\u00fcsli",
            "calories_per_serving": 465,
            "protein_grams": 90,
            "carbohydrates_grams": 58,
            "fat_grams": 26
        },
        {
            "name": "Pop-corn",
            "calories_per_serving": 144,
            "protein_grams": 75,
            "carbohydrates_grams": 82,
            "fat_grams": 49
        },
        {
            "name": "Special Flakes Bran Flakes",
            "calories_per_serving": 567,
            "protein_grams": 5,
            "carbohydrates_grams": 19,
            "fat_grams": 19
        },
        {
            "name": "Penne rigate",
            "calories_per_serving": 494,
            "protein_grams": 90,
            "carbohydrates_grams": 21,
            "fat_grams": 52
        },
        {
            "name": "Crespo, small pitted ripe olives",
            "calories_per_serving": 412,
            "protein_grams": 96,
            "carbohydrates_grams": 68,
            "fat_grams": 83
        },
        {
            "name": "Krombacher Pils",
            "calories_per_serving": 533,
            "protein_grams": 92,
            "carbohydrates_grams": 12,
            "fat_grams": 21
        },
        {
            "name": "Daim Bar",
            "calories_per_serving": 159,
            "protein_grams": 28,
            "carbohydrates_grams": 69,
            "fat_grams": 3
        },
        {
            "name": "S\u00fc\u00dfstoff Tabletten",
            "calories_per_serving": 53,
            "protein_grams": 96,
            "carbohydrates_grams": 47,
            "fat_grams": 10
        },
        {
            "name": "cerave",
            "calories_per_serving": 90,
            "protein_grams": 36,
            "carbohydrates_grams": 81,
            "fat_grams": 3
        },
        {
            "name": "Soft Cake Raspberry",
            "calories_per_serving": 268,
            "protein_grams": 20,
            "carbohydrates_grams": 23,
            "fat_grams": 40
        },

        {
            "name": "Baby Carottes",
            "calories_per_serving": 445,
            "protein_grams": 68,
            "carbohydrates_grams": 46,
            "fat_grams": 94
        },
        {
            "name": "Toblerone Dark Chocolate Bar",
            "calories_per_serving": 261,
            "protein_grams": 44,
            "carbohydrates_grams": 51,
            "fat_grams": 96
        },
        {
            "name": "Pot De Cornichon 670g Et 360g Egoutt\u00e9s",
            "calories_per_serving": 472,
            "protein_grams": 45,
            "carbohydrates_grams": 46,
            "fat_grams": 54
        },
        {
            "name": "White chocolate with coconut flakes and cornflakes, coconut flakes and cornflakes",
            "calories_per_serving": 459,
            "protein_grams": 77,
            "carbohydrates_grams": 78,
            "fat_grams": 85
        },
        {
            "name": "Pur Arabica Moulu biologique",
            "calories_per_serving": 380,
            "protein_grams": 75,
            "carbohydrates_grams": 40,
            "fat_grams": 54
        },
        {
            "name": "GALLETAS SANDW. Chocolate VITALDAY",
            "calories_per_serving": 362,
            "protein_grams": 37,
            "carbohydrates_grams": 66,
            "fat_grams": 40
        },
        {
            "name": "Lustucru couscous facile sc 500g",
            "calories_per_serving": 494,
            "protein_grams": 68,
            "carbohydrates_grams": 13,
            "fat_grams": 78
        },
        {
            "name": "Jif peanut butter",
            "calories_per_serving": 112,
            "protein_grams": 4,
            "carbohydrates_grams": 45,
            "fat_grams": 23
        },
        {
            "name": "Diet Coke",
            "calories_per_serving": 397,
            "protein_grams": 100,
            "carbohydrates_grams": 26,
            "fat_grams": 15
        },
        {
            "name": "Asperges blanches",
            "calories_per_serving": 504,
            "protein_grams": 63,
            "carbohydrates_grams": 64,
            "fat_grams": 25
        },
        {
            "name": "Zumo de Manzana",
            "calories_per_serving": 364,
            "protein_grams": 89,
            "carbohydrates_grams": 43,
            "fat_grams": 72
        },
        {
            "name": "Croissants Cacao Noisette",
            "calories_per_serving": 326,
            "protein_grams": 96,
            "carbohydrates_grams": 23,
            "fat_grams": 64
        },
        {
            "name": "abc classic svje\u017ei krem sir",
            "calories_per_serving": 93,
            "protein_grams": 70,
            "carbohydrates_grams": 73,
            "fat_grams": 100
        },
        {
            "name": "Looping",
            "calories_per_serving": 520,
            "protein_grams": 30,
            "carbohydrates_grams": 44,
            "fat_grams": 63
        },
        {
            "name": "Haricots verts extra fins",
            "calories_per_serving": 431,
            "protein_grams": 40,
            "carbohydrates_grams": 79,
            "fat_grams": 68
        },
        {
            "name": "Yaourts brass\u00e9s nature au lait entier 16 x 125 g",
            "calories_per_serving": 490,
            "protein_grams": 3,
            "carbohydrates_grams": 13,
            "fat_grams": 1
        },
        {
            "name": "Haricots blancs",
            "calories_per_serving": 215,
            "protein_grams": 38,
            "carbohydrates_grams": 28,
            "fat_grams": 74
        },
        {
            "name": "Toblerone",
            "calories_per_serving": 340,
            "protein_grams": 90,
            "carbohydrates_grams": 20,
            "fat_grams": 37
        },
        {
            "name": "Caldo Natural de Pollastre Aneto",
            "calories_per_serving": 408,
            "protein_grams": 69,
            "carbohydrates_grams": 78,
            "fat_grams": 11
        },
        {
            "name": "Cheerios",
            "calories_per_serving": 369,
            "protein_grams": 50,
            "carbohydrates_grams": 89,
            "fat_grams": 69
        },
        {
            "name": "Pure Life",
            "calories_per_serving": 352,
            "protein_grams": 98,
            "carbohydrates_grams": 48,
            "fat_grams": 96
        },
        {
            "name": "Burger Buns",
            "calories_per_serving": 398,
            "protein_grams": 98,
            "carbohydrates_grams": 90,
            "fat_grams": 72
        },
        {
            "name": "Th\u00e9 infus\u00e9 glac\u00e9 bio saveur menthe du Maroc",
            "calories_per_serving": 58,
            "protein_grams": 69,
            "carbohydrates_grams": 18,
            "fat_grams": 21
        },
        {
            "name": "Cerave",
            "calories_per_serving": 450,
            "protein_grams": 32,
            "carbohydrates_grams": 19,
            "fat_grams": 50
        },
        {
            "name": "A\u00efoli sauce \u00e0 l'ail",
            "calories_per_serving": 358,
            "protein_grams": 84,
            "carbohydrates_grams": 13,
            "fat_grams": 41
        },
        {
            "name": "Thon Entier",
            "calories_per_serving": 104,
            "protein_grams": 12,
            "carbohydrates_grams": 48,
            "fat_grams": 10
        },
        {
            "name": "Spare Ribs",
            "calories_per_serving": 314,
            "protein_grams": 69,
            "carbohydrates_grams": 75,
            "fat_grams": 48
        },
        {
            "name": "Dessert v\u00e9g\u00e9tal chocolat",
            "calories_per_serving": 545,
            "protein_grams": 88,
            "carbohydrates_grams": 42,
            "fat_grams": 16
        },
        {
            "name": "Haricots blancs tomate",
            "calories_per_serving": 72,
            "protein_grams": 31,
            "carbohydrates_grams": 72,
            "fat_grams": 71
        },
        {
            "name": "Kirkland purified water",
            "calories_per_serving": 375,
            "protein_grams": 45,
            "carbohydrates_grams": 15,
            "fat_grams": 20
        },
        {
            "name": "Reine Butter Milch",
            "calories_per_serving": 60,
            "protein_grams": 93,
            "carbohydrates_grams": 15,
            "fat_grams": 94
        },
        {
            "name": "Oats & honey clusters with toasted coconut granola",
            "calories_per_serving": 258,
            "protein_grams": 46,
            "carbohydrates_grams": 90,
            "fat_grams": 19
        },
        {
            "name": "Saucisson sec pur porc",
            "calories_per_serving": 397,
            "protein_grams": 90,
            "carbohydrates_grams": 60,
            "fat_grams": 85
        },
        {
            "name": "Sardines de Bretagne pr\u00e9par\u00e9es \u00e0 l'ancienne \u00e0 l'huile d'olive",
            "calories_per_serving": 152,
            "protein_grams": 18,
            "carbohydrates_grams": 22,
            "fat_grams": 38
        },
        {
            "name": "Pousses de Mungo Mungosprossen",
            "calories_per_serving": 291,
            "protein_grams": 82,
            "carbohydrates_grams": 67,
            "fat_grams": 90
        },
        {
            "name": "Kopiccino",
            "calories_per_serving": 57,
            "protein_grams": 97,
            "carbohydrates_grams": 68,
            "fat_grams": 7
        },
        {
            "name": "Samt Marmelade Himbeere",
            "calories_per_serving": 511,
            "protein_grams": 48,
            "carbohydrates_grams": 1,
            "fat_grams": 41
        },
        {
            "name": "HELDENKRAUT B\u00e4rlauch-Chili-Pesto",
            "calories_per_serving": 316,
            "protein_grams": 30,
            "carbohydrates_grams": 64,
            "fat_grams": 76
        },
        {
            "name": "Apfelsaft Direktsaft, naturtr\u00fcb",
            "calories_per_serving": 396,
            "protein_grams": 88,
            "carbohydrates_grams": 32,
            "fat_grams": 25
        },
        {
            "name": "Smooth and creamy chocolate instant cappuccino coffee beverage mix, chocolate",
            "calories_per_serving": 135,
            "protein_grams": 96,
            "carbohydrates_grams": 76,
            "fat_grams": 63
        },
        {
            "name": "PLAQUETTE 250G DOUX",
            "calories_per_serving": 445,
            "protein_grams": 98,
            "carbohydrates_grams": 99,
            "fat_grams": 21
        },
        {
            "name": "Rapeseed oil",
            "calories_per_serving": 451,
            "protein_grams": 31,
            "carbohydrates_grams": 61,
            "fat_grams": 32
        },
        {
            "name": "Maggi",
            "calories_per_serving": 336,
            "protein_grams": 8,
            "carbohydrates_grams": 74,
            "fat_grams": 7
        },
        {
            "name": "Nutella",
            "calories_per_serving": 71,
            "protein_grams": 83,
            "carbohydrates_grams": 25,
            "fat_grams": 53
        },
        {
            "name": "Ma\u00efs extra croquant",
            "calories_per_serving": 274,
            "protein_grams": 26,
            "carbohydrates_grams": 65,
            "fat_grams": 42
        },
        {
            "name": "Sriracha Hot Chili Sauce",
            "calories_per_serving": 133,
            "protein_grams": 30,
            "carbohydrates_grams": 64,
            "fat_grams": 74
        },
        {
            "name": "Grilled pepper bruschetta spread, peperoni grigliati",
            "calories_per_serving": 198,
            "protein_grams": 61,
            "carbohydrates_grams": 37,
            "fat_grams": 20
        },
        {
            "name": "Chips Ahoy Original",
            "calories_per_serving": 535,
            "protein_grams": 41,
            "carbohydrates_grams": 43,
            "fat_grams": 29
        },
        {
            "name": "Cocktails sauce",
            "calories_per_serving": 252,
            "protein_grams": 14,
            "carbohydrates_grams": 24,
            "fat_grams": 5
        },
        {
            "name": "Chocolate Orange Milk",
            "calories_per_serving": 263,
            "protein_grams": 81,
            "carbohydrates_grams": 98,
            "fat_grams": 10
        },
        {
            "name": "Gem\u00fcsepfanne Franz\u00f6sische Arr",
            "calories_per_serving": 106,
            "protein_grams": 34,
            "carbohydrates_grams": 60,
            "fat_grams": 65
        },
        {
            "name": "Honey Nut Cheerios",
            "calories_per_serving": 524,
            "protein_grams": 72,
            "carbohydrates_grams": 8,
            "fat_grams": 22
        },
        {
            "name": "Peanut butter cups valentines day chocolates",
            "calories_per_serving": 232,
            "protein_grams": 83,
            "carbohydrates_grams": 95,
            "fat_grams": 85
        },
        {
            "name": "Organic Vanilla Almond Milk",
            "calories_per_serving": 94,
            "protein_grams": 33,
            "carbohydrates_grams": 42,
            "fat_grams": 22
        },
        {
            "name": "Mountain Dew",
            "calories_per_serving": 347,
            "protein_grams": 52,
            "carbohydrates_grams": 46,
            "fat_grams": 35
        },
        {
            "name": "Honey bunches of oats",
            "calories_per_serving": 98,
            "protein_grams": 46,
            "carbohydrates_grams": 8,
            "fat_grams": 97
        },
        {
            "name": "protein bar, cinnamon roll",
            "calories_per_serving": 240,
            "protein_grams": 65,
            "carbohydrates_grams": 75,
            "fat_grams": 10
        },
        {
            "name": "Choco Bananas minis",
            "calories_per_serving": 50,
            "protein_grams": 16,
            "carbohydrates_grams": 3,
            "fat_grams": 26
        },
        {
            "name": "Tisane Drainage et \u00e9limination",
            "calories_per_serving": 191,
            "protein_grams": 84,
            "carbohydrates_grams": 19,
            "fat_grams": 84
        },
        {
            "name": "Toblerone chocolate bar milk",
            "calories_per_serving": 73,
            "protein_grams": 54,
            "carbohydrates_grams": 92,
            "fat_grams": 50
        },
        {
            "name": "Toblerone",
            "calories_per_serving": 441,
            "protein_grams": 82,
            "carbohydrates_grams": 100,
            "fat_grams": 37
        },
        {
            "name": "Gl\u00fcck Passiert aus Himbeeren",
            "calories_per_serving": 161,
            "protein_grams": 68,
            "carbohydrates_grams": 38,
            "fat_grams": 55
        },
        {
            "name": "Nestle Pure Life Water",
            "calories_per_serving": 464,
            "protein_grams": 7,
            "carbohydrates_grams": 27,
            "fat_grams": 91
        },
        {
            "name": "Cola Zero Zero",
            "calories_per_serving": 516,
            "protein_grams": 37,
            "carbohydrates_grams": 91,
            "fat_grams": 41
        },
        {
            "name": "Salmas horneadas",
            "calories_per_serving": 597,
            "protein_grams": 94,
            "carbohydrates_grams": 31,
            "fat_grams": 58
        },
        {
            "name": "Granola Big Crunchy & Cinnamon",
            "calories_per_serving": 527,
            "protein_grams": 12,
            "carbohydrates_grams": 76,
            "fat_grams": 100
        },
        {
            "name": "Zitronen saft",
            "calories_per_serving": 56,
            "protein_grams": 54,
            "carbohydrates_grams": 21,
            "fat_grams": 29
        },
        {
            "name": "Water, Purified",
            "calories_per_serving": 489,
            "protein_grams": 34,
            "carbohydrates_grams": 64,
            "fat_grams": 45
        },
        {
            "name": "Quaker Oats Old Fashioned Oatmeal 18 Ounce Paper Cannister",
            "calories_per_serving": 130,
            "protein_grams": 19,
            "carbohydrates_grams": 69,
            "fat_grams": 86
        },
        {
            "name": "Skippy, creamy peanut butter, creamy",
            "calories_per_serving": 453,
            "protein_grams": 9,
            "carbohydrates_grams": 39,
            "fat_grams": 77
        },
        {
            "name": "Cinnamon Oat Granola with Flax Seeds",
            "calories_per_serving": 512,
            "protein_grams": 89,
            "carbohydrates_grams": 2,
            "fat_grams": 38
        },
        {
            "name": "Crunchy honey roasted",
            "calories_per_serving": 258,
            "protein_grams": 7,
            "carbohydrates_grams": 100,
            "fat_grams": 62
        },
        {
            "name": "Balsamic vinegar of modena",
            "calories_per_serving": 236,
            "protein_grams": 7,
            "carbohydrates_grams": 19,
            "fat_grams": 98
        },
        {
            "name": "Petites madeleines",
            "calories_per_serving": 343,
            "protein_grams": 50,
            "carbohydrates_grams": 85,
            "fat_grams": 46
        },
        {
            "name": "Soupe butternut patate douce",
            "calories_per_serving": 280,
            "protein_grams": 99,
            "carbohydrates_grams": 84,
            "fat_grams": 66
        },
        {
            "name": "Getr\u00e4nke - Apfel klar",
            "calories_per_serving": 74,
            "protein_grams": 84,
            "carbohydrates_grams": 89,
            "fat_grams": 12
        },
        {
            "name": "Baiweifu Foods, Stew Beef & Mutton Seasoning Powder, Stew Beef & Mutton",
            "calories_per_serving": 348,
            "protein_grams": 33,
            "carbohydrates_grams": 92,
            "fat_grams": 83
        },
        {
            "name": "Vitalday",
            "calories_per_serving": 579,
            "protein_grams": 91,
            "carbohydrates_grams": 77,
            "fat_grams": 26
        },
        {
            "name": "Beyond Burger Plant-Based Patties",
            "calories_per_serving": 368,
            "protein_grams": 14,
            "carbohydrates_grams": 91,
            "fat_grams": 50
        },
        {
            "name": "Nutoka noisette nougat cr\u00e8me",
            "calories_per_serving": 563,
            "protein_grams": 9,
            "carbohydrates_grams": 55,
            "fat_grams": 88
        },
        {
            "name": "Red curry poulet et riz parfum\u00e9",
            "calories_per_serving": 273,
            "protein_grams": 22,
            "carbohydrates_grams": 63,
            "fat_grams": 55
        },
        {
            "name": "Rohrohrzucker",
            "calories_per_serving": 263,
            "protein_grams": 98,
            "carbohydrates_grams": 50,
            "fat_grams": 81
        },
        {
            "name": "Light ketchup",
            "calories_per_serving": 153,
            "protein_grams": 8,
            "carbohydrates_grams": 1,
            "fat_grams": 3
        },
        {
            "name": "Gouda light w\u00fcrfel",
            "calories_per_serving": 270,
            "protein_grams": 43,
            "carbohydrates_grams": 77,
            "fat_grams": 25
        },
        {
            "name": "Bio Organic Bl\u00fcten Honig",
            "calories_per_serving": 460,
            "protein_grams": 43,
            "carbohydrates_grams": 74,
            "fat_grams": 18
        },
        {
            "name": "Thin-sliced bread, good seed",
            "calories_per_serving": 197,
            "protein_grams": 76,
            "carbohydrates_grams": 88,
            "fat_grams": 27
        },
        {
            "name": "Kraft - Macaroni & Cheese box",
            "calories_per_serving": 221,
            "protein_grams": 48,
            "carbohydrates_grams": 76,
            "fat_grams": 52
        },
        {
            "name": "Quaker Instant Oatmeal Original",
            "calories_per_serving": 453,
            "protein_grams": 15,
            "carbohydrates_grams": 50,
            "fat_grams": 59
        },
        {
            "name": "Reduced fat super chunk peanut butter spread",
            "calories_per_serving": 357,
            "protein_grams": 94,
            "carbohydrates_grams": 4,
            "fat_grams": 95
        },
        {
            "name": "Pure Pumpkin Puree",
            "calories_per_serving": 378,
            "protein_grams": 74,
            "carbohydrates_grams": 38,
            "fat_grams": 49
        },
        {
            "name": "Tomato ketchup",
            "calories_per_serving": 574,
            "protein_grams": 5,
            "carbohydrates_grams": 66,
            "fat_grams": 36
        },
        {
            "name": "Gold standard 100% whey",
            "calories_per_serving": 62,
            "protein_grams": 89,
            "carbohydrates_grams": 37,
            "fat_grams": 25
        },
        {
            "name": "Tuna, Chunk Light in Water",
            "calories_per_serving": 345,
            "protein_grams": 5,
            "carbohydrates_grams": 89,
            "fat_grams": 37
        },
        {
            "name": "Chocolate mocha chip light ice cream",
            "calories_per_serving": 574,
            "protein_grams": 51,
            "carbohydrates_grams": 18,
            "fat_grams": 3
        },
        {
            "name": "Ice Cream, Strawberry",
            "calories_per_serving": 118,
            "protein_grams": 44,
            "carbohydrates_grams": 2,
            "fat_grams": 82
        },
        {
            "name": "Caf\u00e9 expresso en grains",
            "calories_per_serving": 463,
            "protein_grams": 81,
            "carbohydrates_grams": 94,
            "fat_grams": 94
        },
        {
            "name": "Thai Noodles Satay sauce",
            "calories_per_serving": 51,
            "protein_grams": 71,
            "carbohydrates_grams": 29,
            "fat_grams": 1
        },
        {
            "name": "Extra virgin olive oil",
            "calories_per_serving": 69,
            "protein_grams": 94,
            "carbohydrates_grams": 51,
            "fat_grams": 88
        },
        {
            "name": "Panzani gansettes 500g",
            "calories_per_serving": 340,
            "protein_grams": 20,
            "carbohydrates_grams": 87,
            "fat_grams": 64
        },
        {
            "name": "Chips Pizza 125G Bret's",
            "calories_per_serving": 178,
            "protein_grams": 39,
            "carbohydrates_grams": 94,
            "fat_grams": 73
        },
        {
            "name": "Fjord",
            "calories_per_serving": 191,
            "protein_grams": 6,
            "carbohydrates_grams": 81,
            "fat_grams": 65
        },
        {
            "name": "Jiff Creamy Peanutbutter",
            "calories_per_serving": 446,
            "protein_grams": 15,
            "carbohydrates_grams": 79,
            "fat_grams": 100
        },
        {
            "name": "Golden Oreo",
            "calories_per_serving": 274,
            "protein_grams": 14,
            "carbohydrates_grams": 73,
            "fat_grams": 47
        },
        {
            "name": "Chocolate con leche con almendras enteras",
            "calories_per_serving": 514,
            "protein_grams": 45,
            "carbohydrates_grams": 44,
            "fat_grams": 3
        },
        {
            "name": "Smoki",
            "calories_per_serving": 516,
            "protein_grams": 47,
            "carbohydrates_grams": 79,
            "fat_grams": 15
        },
        {
            "name": "Kokosmilch",
            "calories_per_serving": 533,
            "protein_grams": 39,
            "carbohydrates_grams": 45,
            "fat_grams": 57
        },
        {
            "name": "Kraft Grated Parmesan Cheese",
            "calories_per_serving": 128,
            "protein_grams": 76,
            "carbohydrates_grams": 5,
            "fat_grams": 33
        },
        {
            "name": "Extra polar ice slim pack",
            "calories_per_serving": 567,
            "protein_grams": 69,
            "carbohydrates_grams": 36,
            "fat_grams": 38
        },
        {
            "name": "Gem\u00fcse Bouillon",
            "calories_per_serving": 488,
            "protein_grams": 74,
            "carbohydrates_grams": 62,
            "fat_grams": 61
        },
        {
            "name": "Dinkel H\u00f6rnchen",
            "calories_per_serving": 310,
            "protein_grams": 68,
            "carbohydrates_grams": 75,
            "fat_grams": 75
        },
        {
            "name": "Granola",
            "calories_per_serving": 314,
            "protein_grams": 58,
            "carbohydrates_grams": 22,
            "fat_grams": 91
        },
        {
            "name": "B\u00e4rlauch Quark",
            "calories_per_serving": 363,
            "protein_grams": 33,
            "carbohydrates_grams": 37,
            "fat_grams": 29
        },
        {
            "name": "Amaranth gepufft",
            "calories_per_serving": 408,
            "protein_grams": 12,
            "carbohydrates_grams": 79,
            "fat_grams": 49
        },
        {
            "name": "Speisequark Magerstufe",
            "calories_per_serving": 359,
            "protein_grams": 66,
            "carbohydrates_grams": 82,
            "fat_grams": 94
        },
        {
            "name": "Chocolat au lait",
            "calories_per_serving": 156,
            "protein_grams": 40,
            "carbohydrates_grams": 60,
            "fat_grams": 95
        },
        {
            "name": "Almond Milk Unsweet Vanilla",
            "calories_per_serving": 313,
            "protein_grams": 26,
            "carbohydrates_grams": 29,
            "fat_grams": 4
        },
        {
            "name": "Kellogg s breakfast cereal",
            "calories_per_serving": 108,
            "protein_grams": 11,
            "carbohydrates_grams": 15,
            "fat_grams": 24
        },
        {
            "name": "Snack factory pretzel crisps crackers original",
            "calories_per_serving": 430,
            "protein_grams": 68,
            "carbohydrates_grams": 22,
            "fat_grams": 24
        },
        {
            "name": "Organic apple cider vinegar with the 'mother'",
            "calories_per_serving": 62,
            "protein_grams": 47,
            "carbohydrates_grams": 22,
            "fat_grams": 4
        },
        {
            "name": "Great value, purified drinking water",
            "calories_per_serving": 454,
            "protein_grams": 28,
            "carbohydrates_grams": 60,
            "fat_grams": 85
        },
        {
            "name": "Sprite",
            "calories_per_serving": 562,
            "protein_grams": 14,
            "carbohydrates_grams": 15,
            "fat_grams": 75
        },
        {
            "name": "Dark chocolate nuts & sea salt",
            "calories_per_serving": 235,
            "protein_grams": 1,
            "carbohydrates_grams": 14,
            "fat_grams": 9
        },
        {
            "name": "Vanilla Blueberry Clusters (Granola)",
            "calories_per_serving": 125,
            "protein_grams": 91,
            "carbohydrates_grams": 66,
            "fat_grams": 2
        },
        {
            "name": "BeKind Amandes et Noix de coco",
            "calories_per_serving": 249,
            "protein_grams": 11,
            "carbohydrates_grams": 65,
            "fat_grams": 15
        },
        {
            "name": "Takis, Tortilla Chips, Fuego",
            "calories_per_serving": 181,
            "protein_grams": 17,
            "carbohydrates_grams": 23,
            "fat_grams": 67
        },
        {
            "name": "Dr. Pepper",
            "calories_per_serving": 239,
            "protein_grams": 70,
            "carbohydrates_grams": 13,
            "fat_grams": 4
        },
        {
            "name": "Gentle teethers organic teething wafers banana sweet potato",
            "calories_per_serving": 129,
            "protein_grams": 11,
            "carbohydrates_grams": 63,
            "fat_grams": 44
        },
        {
            "name": "Shredded wheat original",
            "calories_per_serving": 115,
            "protein_grams": 36,
            "carbohydrates_grams": 81,
            "fat_grams": 81
        },
        {
            "name": "Sylt Hjortron Lakkahillo",
            "calories_per_serving": 116,
            "protein_grams": 20,
            "carbohydrates_grams": 79,
            "fat_grams": 13
        },
        {
            "name": "Franz\u00f6sischer Frischk\u00e4se aus Ziegenmilch",
            "calories_per_serving": 301,
            "protein_grams": 55,
            "carbohydrates_grams": 9,
            "fat_grams": 6
        },
        {
            "name": "Sardines \u00e0 l'Ancienne Label rouge",
            "calories_per_serving": 392,
            "protein_grams": 61,
            "carbohydrates_grams": 40,
            "fat_grams": 8
        },
        {
            "name": "Brillat Savarin Aefine",
            "calories_per_serving": 336,
            "protein_grams": 38,
            "carbohydrates_grams": 74,
            "fat_grams": 69
        },
        {
            "name": "Sardines ",
            "calories_per_serving": 421,
            "protein_grams": 33,
            "carbohydrates_grams": 87,
            "fat_grams": 10
        },
        {
            "name": "Extra virgin olive oil",
            "calories_per_serving": 519,
            "protein_grams": 18,
            "carbohydrates_grams": 20,
            "fat_grams": 43
        },
        {
            "name": "Jelly babies",
            "calories_per_serving": 546,
            "protein_grams": 13,
            "carbohydrates_grams": 36,
            "fat_grams": 26
        },
        {
            "name": "Vegetable broth",
            "calories_per_serving": 353,
            "protein_grams": 20,
            "carbohydrates_grams": 55,
            "fat_grams": 6
        },
        {
            "name": "Picual extra virgin olive oil",
            "calories_per_serving": 471,
            "protein_grams": 57,
            "carbohydrates_grams": 39,
            "fat_grams": 28
        },
        {
            "name": "Chocolate Sprinkles",
            "calories_per_serving": 442,
            "protein_grams": 74,
            "carbohydrates_grams": 59,
            "fat_grams": 31
        },
        {
            "name": "Pate de curry jaune thai",
            "calories_per_serving": 430,
            "protein_grams": 19,
            "carbohydrates_grams": 13,
            "fat_grams": 60
        },
        {
            "name": "P\u00e2te de curry rouge",
            "calories_per_serving": 320,
            "protein_grams": 99,
            "carbohydrates_grams": 30,
            "fat_grams": 92
        },
        {
            "name": "Cheetos Crunchy Flamin' Hot",
            "calories_per_serving": 116,
            "protein_grams": 79,
            "carbohydrates_grams": 77,
            "fat_grams": 80
        },
        {
            "name": "Dhbukk",
            "calories_per_serving": 378,
            "protein_grams": 68,
            "carbohydrates_grams": 77,
            "fat_grams": 96
        },
        {
            "name": "Hortex sok pomidorowy",
            "calories_per_serving": 599,
            "protein_grams": 34,
            "carbohydrates_grams": 7,
            "fat_grams": 10
        },
        {
            "name": "Pepsi twist",
            "calories_per_serving": 440,
            "protein_grams": 8,
            "carbohydrates_grams": 46,
            "fat_grams": 79
        },
        {
            "name": "Raps\u00f6l",
            "calories_per_serving": 419,
            "protein_grams": 17,
            "carbohydrates_grams": 31,
            "fat_grams": 86
        },
        {
            "name": "Coca-Cola Zero",
            "calories_per_serving": 244,
            "protein_grams": 69,
            "carbohydrates_grams": 38,
            "fat_grams": 49
        },
        {
            "name": "Unsweetened creamy peanut butter, creamy",
            "calories_per_serving": 429,
            "protein_grams": 100,
            "carbohydrates_grams": 67,
            "fat_grams": 39
        },
        {
            "name": "Crunchy muesli",
            "calories_per_serving": 243,
            "protein_grams": 68,
            "carbohydrates_grams": 16,
            "fat_grams": 41
        },
        {
            "name": "doritos",
            "calories_per_serving": 530,
            "protein_grams": 11,
            "carbohydrates_grams": 95,
            "fat_grams": 67
        },
        {
            "name": "Keto Nut Granola",
            "calories_per_serving": 421,
            "protein_grams": 7,
            "carbohydrates_grams": 6,
            "fat_grams": 26
        },
        {
            "name": "peanuts with Chili",
            "calories_per_serving": 331,
            "protein_grams": 87,
            "carbohydrates_grams": 75,
            "fat_grams": 99
        },
        {
            "name": "Apfelmus Golden Delicious",
            "calories_per_serving": 121,
            "protein_grams": 89,
            "carbohydrates_grams": 77,
            "fat_grams": 37
        },
        {
            "name": "Burger made from plants",
            "calories_per_serving": 69,
            "protein_grams": 45,
            "carbohydrates_grams": 77,
            "fat_grams": 29
        },
        {
            "name": "Crackers",
            "calories_per_serving": 322,
            "protein_grams": 24,
            "carbohydrates_grams": 59,
            "fat_grams": 16
        },
        {
            "name": "St Hubert Avoine Le chocolat",
            "calories_per_serving": 318,
            "protein_grams": 74,
            "carbohydrates_grams": 68,
            "fat_grams": 81
        },
        {
            "name": "Pain de mie extra moelleux",
            "calories_per_serving": 588,
            "protein_grams": 26,
            "carbohydrates_grams": 90,
            "fat_grams": 8
        },
        {
            "name": "Saint Moret  L\u00e9ger 8%mg",
            "calories_per_serving": 452,
            "protein_grams": 18,
            "carbohydrates_grams": 97,
            "fat_grams": 2
        },
        {
            "name": "Traders Joe's, Baking Powder",
            "calories_per_serving": 362,
            "protein_grams": 35,
            "carbohydrates_grams": 62,
            "fat_grams": 91
        },
        {
            "name": "Goldfish",
            "calories_per_serving": 97,
            "protein_grams": 23,
            "carbohydrates_grams": 27,
            "fat_grams": 54
        },
        {
            "name": "Crunchy Oats 'N Honey Granola Bar",
            "calories_per_serving": 436,
            "protein_grams": 8,
            "carbohydrates_grams": 18,
            "fat_grams": 39
        },
        {
            "name": "Sriracha Chili Sauce",
            "calories_per_serving": 434,
            "protein_grams": 88,
            "carbohydrates_grams": 45,
            "fat_grams": 58
        },
        {
            "name": "Peanut butter",
            "calories_per_serving": 478,
            "protein_grams": 80,
            "carbohydrates_grams": 71,
            "fat_grams": 10
        },
        {
            "name": "Classic",
            "calories_per_serving": 146,
            "protein_grams": 88,
            "carbohydrates_grams": 96,
            "fat_grams": 8
        },
        {
            "name": "Corn Flakes",
            "calories_per_serving": 383,
            "protein_grams": 82,
            "carbohydrates_grams": 84,
            "fat_grams": 21
        },
        {
            "name": "Classic hummus",
            "calories_per_serving": 112,
            "protein_grams": 23,
            "carbohydrates_grams": 16,
            "fat_grams": 88
        },
        {
            "name": "Frank's Red Hot Original",
            "calories_per_serving": 71,
            "protein_grams": 87,
            "carbohydrates_grams": 28,
            "fat_grams": 88
        },
        {
            "name": "Marshmallow fluff",
            "calories_per_serving": 463,
            "protein_grams": 2,
            "carbohydrates_grams": 82,
            "fat_grams": 59
        },
        {
            "name": "100% whole wheat bread, 100% whole wheat",
            "calories_per_serving": 295,
            "protein_grams": 40,
            "carbohydrates_grams": 41,
            "fat_grams": 69
        },
        {
            "name": "Organic apple cider vinegar with the 'mother'",
            "calories_per_serving": 410,
            "protein_grams": 60,
            "carbohydrates_grams": 91,
            "fat_grams": 57
        },
        {
            "name": "Nutritional Yeast",
            "calories_per_serving": 291,
            "protein_grams": 100,
            "carbohydrates_grams": 15,
            "fat_grams": 81
        },
        {
            "name": "Silken tofu firm",
            "calories_per_serving": 563,
            "protein_grams": 89,
            "carbohydrates_grams": 79,
            "fat_grams": 94
        },
        {
            "name": "Organic raw honey",
            "calories_per_serving": 70,
            "protein_grams": 92,
            "carbohydrates_grams": 30,
            "fat_grams": 93
        },
        {
            "name": "Purified Drinking Water",
            "calories_per_serving": 356,
            "protein_grams": 87,
            "carbohydrates_grams": 38,
            "fat_grams": 39
        },
        {
            "name": "Granola",
            "calories_per_serving": 81,
            "protein_grams": 48,
            "carbohydrates_grams": 9,
            "fat_grams": 100
        },
        {
            "name": "Greek Yogurt Whole Milk Plain",
            "calories_per_serving": 505,
            "protein_grams": 94,
            "carbohydrates_grams": 83,
            "fat_grams": 40
        },
        {
            "name": "Icelandic style strained non-fat yogurt vanilla",
            "calories_per_serving": 480,
            "protein_grams": 57,
            "carbohydrates_grams": 73,
            "fat_grams": 58
        },
        {
            "name": "Eau de coco",
            "calories_per_serving": 559,
            "protein_grams": 20,
            "carbohydrates_grams": 100,
            "fat_grams": 98
        },
        {
            "name": "Dark chocolate covered pretzels with peppermint pieces, peppermint",
            "calories_per_serving": 568,
            "protein_grams": 44,
            "carbohydrates_grams": 82,
            "fat_grams": 36
        },
        {
            "name": "Creamy almond butter",
            "calories_per_serving": 91,
            "protein_grams": 12,
            "carbohydrates_grams": 44,
            "fat_grams": 11
        },
        {
            "name": "Sorbet au citron",
            "calories_per_serving": 302,
            "protein_grams": 53,
            "carbohydrates_grams": 76,
            "fat_grams": 78
        },
        {
            "name": "Instant Long Grain Rice",
            "calories_per_serving": 345,
            "protein_grams": 89,
            "carbohydrates_grams": 36,
            "fat_grams": 17
        },
        {
            "name": "Bq.boeuf Prov.mo W.watche,",
            "calories_per_serving": 349,
            "protein_grams": 94,
            "carbohydrates_grams": 90,
            "fat_grams": 24
        },
        {
            "name": "Orangina - Cool Can",
            "calories_per_serving": 167,
            "protein_grams": 13,
            "carbohydrates_grams": 33,
            "fat_grams": 21
        },
        {
            "name": "Orange mango passion fruit 100% fruit premium smoothie",
            "calories_per_serving": 51,
            "protein_grams": 67,
            "carbohydrates_grams": 62,
            "fat_grams": 99
        },
        {
            "name": "Curry Sauce",
            "calories_per_serving": 462,
            "protein_grams": 37,
            "carbohydrates_grams": 6,
            "fat_grams": 64
        },
        {
            "name": "Der Markenzwieback",
            "calories_per_serving": 500,
            "protein_grams": 63,
            "carbohydrates_grams": 43,
            "fat_grams": 43
        },
        {
            "name": "Sonntags Br\u00f6tchen",
            "calories_per_serving": 126,
            "protein_grams": 78,
            "carbohydrates_grams": 87,
            "fat_grams": 31
        },
        {
            "name": "Aloe Vera",
            "calories_per_serving": 417,
            "protein_grams": 62,
            "carbohydrates_grams": 38,
            "fat_grams": 36
        },
        {
            "name": "All-In-One Ramen - Nouilles Japonnaises",
            "calories_per_serving": 321,
            "protein_grams": 40,
            "carbohydrates_grams": 92,
            "fat_grams": 73
        },
        {
            "name": "Lebanese Style Falafel",
            "calories_per_serving": 454,
            "protein_grams": 91,
            "carbohydrates_grams": 76,
            "fat_grams": 74
        },
        {
            "name": "Orval Trappist",
            "calories_per_serving": 260,
            "protein_grams": 95,
            "carbohydrates_grams": 86,
            "fat_grams": 36
        },
        {
            "name": "Pan tostado",
            "calories_per_serving": 380,
            "protein_grams": 66,
            "carbohydrates_grams": 52,
            "fat_grams": 35
        },
        {
            "name": "Dairy Milk Fruit and Nut Chocolate Bar",
            "calories_per_serving": 51,
            "protein_grams": 58,
            "carbohydrates_grams": 87,
            "fat_grams": 89
        },
        {
            "name": "Ferrero Rocher",
            "calories_per_serving": 538,
            "protein_grams": 21,
            "carbohydrates_grams": 95,
            "fat_grams": 71
        },
        {
            "name": "100% natural broth, chicken",
            "calories_per_serving": 539,
            "protein_grams": 55,
            "carbohydrates_grams": 66,
            "fat_grams": 68
        },
        {
            "name": "Caldo de pescado natural",
            "calories_per_serving": 325,
            "protein_grams": 51,
            "carbohydrates_grams": 28,
            "fat_grams": 63
        },
        {
            "name": "Chobani Plain Greek Yogurt (0.5% fat)",
            "calories_per_serving": 112,
            "protein_grams": 21,
            "carbohydrates_grams": 19,
            "fat_grams": 41
        },
        {
            "name": "Belvita Breakfast Soft Bakes, Red Berries",
            "calories_per_serving": 190,
            "protein_grams": 22,
            "carbohydrates_grams": 15,
            "fat_grams": 61
        },
        {
            "name": "Quaker rice cakes apple cinnamon",
            "calories_per_serving": 147,
            "protein_grams": 66,
            "carbohydrates_grams": 78,
            "fat_grams": 74
        },
        {
            "name": "Beyond Burger",
            "calories_per_serving": 450,
            "protein_grams": 46,
            "carbohydrates_grams": 74,
            "fat_grams": 76
        },
        {
            "name": "Oat milk",
            "calories_per_serving": 203,
            "protein_grams": 18,
            "carbohydrates_grams": 75,
            "fat_grams": 39
        },
        {
            "name": "Sonnenblumenmagerine",
            "calories_per_serving": 225,
            "protein_grams": 69,
            "carbohydrates_grams": 17,
            "fat_grams": 3
        },
        {
            "name": "Campbell Tomato Soup",
            "calories_per_serving": 347,
            "protein_grams": 34,
            "carbohydrates_grams": 36,
            "fat_grams": 84
        },
        {
            "name": "Unt de mas\u0103",
            "calories_per_serving": 193,
            "protein_grams": 95,
            "carbohydrates_grams": 82,
            "fat_grams": 54
        },
        {
            "name": "Non Dairy Oat Beverage",
            "calories_per_serving": 364,
            "protein_grams": 48,
            "carbohydrates_grams": 85,
            "fat_grams": 76
        },
        {
            "name": "Unsweetened oatmilk barista blend",
            "calories_per_serving": 298,
            "protein_grams": 89,
            "carbohydrates_grams": 39,
            "fat_grams": 98
        },
        {
            "name": "Erdbeer Banane Smoothie",
            "calories_per_serving": 156,
            "protein_grams": 24,
            "carbohydrates_grams": 85,
            "fat_grams": 37
        },
        {
            "name": "Westf\u00e4lischer Linsen-Eintopf mit Essig",
            "calories_per_serving": 125,
            "protein_grams": 84,
            "carbohydrates_grams": 35,
            "fat_grams": 47
        },
        {
            "name": "Weidevollmilch",
            "calories_per_serving": 383,
            "protein_grams": 74,
            "carbohydrates_grams": 86,
            "fat_grams": 91
        },
        {
            "name": "Soba",
            "calories_per_serving": 483,
            "protein_grams": 9,
            "carbohydrates_grams": 60,
            "fat_grams": 71
        },
        {
            "name": "Poland springs origin",
            "calories_per_serving": 574,
            "protein_grams": 81,
            "carbohydrates_grams": 99,
            "fat_grams": 14
        },
        {
            "name": "Baby Carottes et Radis \u00e0 croquer",
            "calories_per_serving": 581,
            "protein_grams": 3,
            "carbohydrates_grams": 77,
            "fat_grams": 42
        },
        {
            "name": "Filets de poulet rotis",
            "calories_per_serving": 121,
            "protein_grams": 22,
            "carbohydrates_grams": 14,
            "fat_grams": 81
        },
        {
            "name": "Snoep tomaten",
            "calories_per_serving": 291,
            "protein_grams": 24,
            "carbohydrates_grams": 83,
            "fat_grams": 62
        },
        {
            "name": "POMEGRANATE",
            "calories_per_serving": 147,
            "protein_grams": 57,
            "carbohydrates_grams": 91,
            "fat_grams": 49
        },
        {
            "name": "Peanut Butter",
            "calories_per_serving": 587,
            "protein_grams": 13,
            "carbohydrates_grams": 61,
            "fat_grams": 33
        },
        {
            "name": "Purified drinking water",
            "calories_per_serving": 582,
            "protein_grams": 29,
            "carbohydrates_grams": 41,
            "fat_grams": 41
        },
        {
            "name": "Lucky charms",
            "calories_per_serving": 51,
            "protein_grams": 57,
            "carbohydrates_grams": 11,
            "fat_grams": 41
        },
        {
            "name": "Whole kernel corn",
            "calories_per_serving": 421,
            "protein_grams": 55,
            "carbohydrates_grams": 57,
            "fat_grams": 63
        },
        {
            "name": "Fruit snacks",
            "calories_per_serving": 264,
            "protein_grams": 49,
            "carbohydrates_grams": 6,
            "fat_grams": 50
        },
        {
            "name": "creamy peanut butter",
            "calories_per_serving": 357,
            "protein_grams": 22,
            "carbohydrates_grams": 34,
            "fat_grams": 50
        },
        {
            "name": "Creamy Peanut Butter",
            "calories_per_serving": 164,
            "protein_grams": 43,
            "carbohydrates_grams": 41,
            "fat_grams": 53
        },
        {
            "name": "Chick pea",
            "calories_per_serving": 197,
            "protein_grams": 67,
            "carbohydrates_grams": 62,
            "fat_grams": 54
        },
        {
            "name": "Less sodium soy sauce, soy",
            "calories_per_serving": 420,
            "protein_grams": 79,
            "carbohydrates_grams": 76,
            "fat_grams": 66
        },
        {
            "name": "Blueberry Fig Bar",
            "calories_per_serving": 301,
            "protein_grams": 39,
            "carbohydrates_grams": 89,
            "fat_grams": 13
        },
        {
            "name": "Coca Cola Zero",
            "calories_per_serving": 110,
            "protein_grams": 22,
            "carbohydrates_grams": 51,
            "fat_grams": 49
        },
        {
            "name": "Preserves strawberry",
            "calories_per_serving": 131,
            "protein_grams": 27,
            "carbohydrates_grams": 93,
            "fat_grams": 70
        },
        {
            "name": "Natural Creamy Peanut Butter",
            "calories_per_serving": 93,
            "protein_grams": 17,
            "carbohydrates_grams": 9,
            "fat_grams": 80
        },
        {
            "name": "Organic cereal",
            "calories_per_serving": 120,
            "protein_grams": 99,
            "carbohydrates_grams": 21,
            "fat_grams": 32
        },
        {
            "name": "Love Crunch",
            "calories_per_serving": 542,
            "protein_grams": 37,
            "carbohydrates_grams": 69,
            "fat_grams": 24
        },
        {
            "name": "Swiss milk chocolate bar",
            "calories_per_serving": 593,
            "protein_grams": 47,
            "carbohydrates_grams": 25,
            "fat_grams": 54
        },
        {
            "name": "Nissin, top ramen, ramen noodle soup, chicken",
            "calories_per_serving": 325,
            "protein_grams": 66,
            "carbohydrates_grams": 9,
            "fat_grams": 72
        },
        {
            "name": "Ezekiel sprouted grain english muffins",
            "calories_per_serving": 191,
            "protein_grams": 41,
            "carbohydrates_grams": 66,
            "fat_grams": 42
        },
        {
            "name": "Food for life, ezekiel 4:9, sprouted grain tortillas",
            "calories_per_serving": 129,
            "protein_grams": 99,
            "carbohydrates_grams": 20,
            "fat_grams": 79
        },
        {
            "name": "Unsalted Mixed Nuts",
            "calories_per_serving": 60,
            "protein_grams": 53,
            "carbohydrates_grams": 81,
            "fat_grams": 63
        },
        {
            "name": "Maple Syrup",
            "calories_per_serving": 121,
            "protein_grams": 47,
            "carbohydrates_grams": 58,
            "fat_grams": 85
        },
        {
            "name": "Pepsi",
            "calories_per_serving": 336,
            "protein_grams": 5,
            "carbohydrates_grams": 100,
            "fat_grams": 38
        },
        {
            "name": "Diet 12floz Can",
            "calories_per_serving": 481,
            "protein_grams": 17,
            "carbohydrates_grams": 32,
            "fat_grams": 54
        },
        {
            "name": "Tomato ketchup, tomato",
            "calories_per_serving": 174,
            "protein_grams": 56,
            "carbohydrates_grams": 19,
            "fat_grams": 53
        },
        {
            "name": "Diet Coke",
            "calories_per_serving": 521,
            "protein_grams": 37,
            "carbohydrates_grams": 51,
            "fat_grams": 56
        },
        {
            "name": "Tajin, clasico seasoning, lime",
            "calories_per_serving": 159,
            "protein_grams": 75,
            "carbohydrates_grams": 49,
            "fat_grams": 37
        },
        {
            "name": "Gluten free peanut satay sauce",
            "calories_per_serving": 161,
            "protein_grams": 72,
            "carbohydrates_grams": 64,
            "fat_grams": 90
        },
        {
            "name": "Hoisin Sauce",
            "calories_per_serving": 519,
            "protein_grams": 33,
            "carbohydrates_grams": 13,
            "fat_grams": 75
        },
        {
            "name": "Takis Fuego - hot chili pepper & lime tortillas chips",
            "calories_per_serving": 228,
            "protein_grams": 46,
            "carbohydrates_grams": 45,
            "fat_grams": 30
        },
        {
            "name": "Tiny, tangy crunchy candy nerds",
            "calories_per_serving": 213,
            "protein_grams": 61,
            "carbohydrates_grams": 56,
            "fat_grams": 41
        },
        {
            "name": "Skinny pop",
            "calories_per_serving": 238,
            "protein_grams": 93,
            "carbohydrates_grams": 13,
            "fat_grams": 16
        },
        {
            "name": "Powdered peanut butter",
            "calories_per_serving": 501,
            "protein_grams": 87,
            "carbohydrates_grams": 64,
            "fat_grams": 78
        },
        {
            "name": "Protein bar",
            "calories_per_serving": 289,
            "protein_grams": 5,
            "carbohydrates_grams": 83,
            "fat_grams": 2
        },
        {
            "name": "Panettone Cioccolato",
            "calories_per_serving": 350,
            "protein_grams": 84,
            "carbohydrates_grams": 47,
            "fat_grams": 43
        },
        {
            "name": "Flageolets Verts Extra-Fins",
            "calories_per_serving": 163,
            "protein_grams": 60,
            "carbohydrates_grams": 100,
            "fat_grams": 77
        },
        {
            "name": "Nacho cheese",
            "calories_per_serving": 533,
            "protein_grams": 96,
            "carbohydrates_grams": 33,
            "fat_grams": 95
        },
        {
            "name": "Nouilles udon \u00e0 cuire",
            "calories_per_serving": 195,
            "protein_grams": 82,
            "carbohydrates_grams": 21,
            "fat_grams": 6
        },
        {
            "name": "Pur\u00e9e au lait",
            "calories_per_serving": 270,
            "protein_grams": 87,
            "carbohydrates_grams": 90,
            "fat_grams": 67
        },
        {
            "name": "Figues Pulled N\u00b06 Ravier 500G NOUVELLE RECOLTE",
            "calories_per_serving": 234,
            "protein_grams": 63,
            "carbohydrates_grams": 1,
            "fat_grams": 35
        },
        {
            "name": "Mayonnaise",
            "calories_per_serving": 185,
            "protein_grams": 90,
            "carbohydrates_grams": 6,
            "fat_grams": 67
        },
        {
            "name": "Me! Extra Hot Chili Noodles",
            "calories_per_serving": 483,
            "protein_grams": 92,
            "carbohydrates_grams": 52,
            "fat_grams": 52
        },
        {
            "name": "Ritz",
            "calories_per_serving": 543,
            "protein_grams": 100,
            "carbohydrates_grams": 23,
            "fat_grams": 55
        },
        {
            "name": "Bisto Gravy",
            "calories_per_serving": 318,
            "protein_grams": 81,
            "carbohydrates_grams": 19,
            "fat_grams": 48
        },
        {
            "name": "Tremo\u00e7os",
            "calories_per_serving": 146,
            "protein_grams": 82,
            "carbohydrates_grams": 99,
            "fat_grams": 97
        },
        {
            "name": "Galettes de riz avec des graines de tournesol",
            "calories_per_serving": 546,
            "protein_grams": 69,
            "carbohydrates_grams": 83,
            "fat_grams": 12
        },
        {
            "name": "D.gus Latt Macc Caramel Nescafe",
            "calories_per_serving": 571,
            "protein_grams": 79,
            "carbohydrates_grams": 55,
            "fat_grams": 78
        },
        {
            "name": "Oreo cookies peanut butter",
            "calories_per_serving": 205,
            "protein_grams": 62,
            "carbohydrates_grams": 95,
            "fat_grams": 37
        },
        {
            "name": "Il mio dado vegetale",
            "calories_per_serving": 430,
            "protein_grams": 18,
            "carbohydrates_grams": 7,
            "fat_grams": 9
        },
        {
            "name": "Spaghetti grossi - No. 5",
            "calories_per_serving": 193,
            "protein_grams": 41,
            "carbohydrates_grams": 38,
            "fat_grams": 70
        },
        {
            "name": "Kinder Maxi",
            "calories_per_serving": 257,
            "protein_grams": 83,
            "carbohydrates_grams": 19,
            "fat_grams": 72
        },
        {
            "name": "De ruijter, fruit sprinkles",
            "calories_per_serving": 185,
            "protein_grams": 84,
            "carbohydrates_grams": 12,
            "fat_grams": 88
        },
        {
            "name": "Instant Noodles Casserole Beef Flavour",
            "calories_per_serving": 292,
            "protein_grams": 58,
            "carbohydrates_grams": 38,
            "fat_grams": 30
        },
        {
            "name": "Cafe",
            "calories_per_serving": 537,
            "protein_grams": 1,
            "carbohydrates_grams": 70,
            "fat_grams": 27
        },
        {
            "name": "Coeur fondant",
            "calories_per_serving": 506,
            "protein_grams": 23,
            "carbohydrates_grams": 82,
            "fat_grams": 84
        },
        {
            "name": "Fritos Lim\u00f3n y sal",
            "calories_per_serving": 546,
            "protein_grams": 31,
            "carbohydrates_grams": 13,
            "fat_grams": 81
        },
        {
            "name": "Sonnenblumen\u00f6l",
            "calories_per_serving": 568,
            "protein_grams": 89,
            "carbohydrates_grams": 66,
            "fat_grams": 7
        },
        {
            "name": "Flocons d'avoine bio",
            "calories_per_serving": 507,
            "protein_grams": 54,
            "carbohydrates_grams": 62,
            "fat_grams": 64
        },
        {
            "name": "pain vegan",
            "calories_per_serving": 388,
            "protein_grams": 33,
            "carbohydrates_grams": 75,
            "fat_grams": 9
        },
        {
            "name": "Peter's yard artisan crispbread",
            "calories_per_serving": 471,
            "protein_grams": 3,
            "carbohydrates_grams": 55,
            "fat_grams": 53
        },
        {
            "name": "Gouda  jeune en tranches",
            "calories_per_serving": 191,
            "protein_grams": 35,
            "carbohydrates_grams": 46,
            "fat_grams": 54
        },
        {
            "name": "Original Oatmilk",
            "calories_per_serving": 510,
            "protein_grams": 63,
            "carbohydrates_grams": 97,
            "fat_grams": 23
        },
        {
            "name": "Just Egg",
            "calories_per_serving": 325,
            "protein_grams": 79,
            "carbohydrates_grams": 21,
            "fat_grams": 43
        },
        {
            "name": "Beyond Burger Plant-Based Patties",
            "calories_per_serving": 252,
            "protein_grams": 85,
            "carbohydrates_grams": 61,
            "fat_grams": 54
        },
        {
            "name": "Frosted strawberry pastries",
            "calories_per_serving": 483,
            "protein_grams": 50,
            "carbohydrates_grams": 93,
            "fat_grams": 52
        },
        {
            "name": "Feldsalat",
            "calories_per_serving": 104,
            "protein_grams": 98,
            "carbohydrates_grams": 32,
            "fat_grams": 43
        },
        {
            "name": "Zaziki",
            "calories_per_serving": 222,
            "protein_grams": 39,
            "carbohydrates_grams": 81,
            "fat_grams": 9
        },
        {
            "name": "Pois chiches en forme de grains de riz",
            "calories_per_serving": 317,
            "protein_grams": 98,
            "carbohydrates_grams": 60,
            "fat_grams": 59
        },
        {
            "name": "Pesto Rosso",
            "calories_per_serving": 311,
            "protein_grams": 29,
            "carbohydrates_grams": 93,
            "fat_grams": 31
        },
        {
            "name": "Dinkel Crunchy",
            "calories_per_serving": 356,
            "protein_grams": 23,
            "carbohydrates_grams": 74,
            "fat_grams": 75
        },
        {
            "name": "Nestle granulated hot chocolate drink mix",
            "calories_per_serving": 440,
            "protein_grams": 72,
            "carbohydrates_grams": 53,
            "fat_grams": 26
        },
        {
            "name": "Triscuit Original with Sea Salt",
            "calories_per_serving": 332,
            "protein_grams": 80,
            "carbohydrates_grams": 44,
            "fat_grams": 64
        },
        {
            "name": "Jasminreis",
            "calories_per_serving": 62,
            "protein_grams": 84,
            "carbohydrates_grams": 53,
            "fat_grams": 43
        },
        {
            "name": "sour cream and onionlays potatoe chips",
            "calories_per_serving": 258,
            "protein_grams": 22,
            "carbohydrates_grams": 36,
            "fat_grams": 41
        },
        {
            "name": "Schwip Schwap Zero",
            "calories_per_serving": 461,
            "protein_grams": 14,
            "carbohydrates_grams": 10,
            "fat_grams": 37
        },
        {
            "name": "100% cocoa Unsweetened Chocolate",
            "calories_per_serving": 136,
            "protein_grams": 71,
            "carbohydrates_grams": 7,
            "fat_grams": 70
        },
        {
            "name": "Goldhirse",
            "calories_per_serving": 445,
            "protein_grams": 28,
            "carbohydrates_grams": 48,
            "fat_grams": 31
        },
        {
            "name": "Holzofen Pizza Fantasia",
            "calories_per_serving": 483,
            "protein_grams": 16,
            "carbohydrates_grams": 61,
            "fat_grams": 89
        },
        {
            "name": "Thai Curry mit Gem\u00fcse und Erdn\u00fcssen",
            "calories_per_serving": 257,
            "protein_grams": 30,
            "carbohydrates_grams": 75,
            "fat_grams": 15
        },
        {
            "name": "southwest chopped salad kit",
            "calories_per_serving": 285,
            "protein_grams": 52,
            "carbohydrates_grams": 28,
            "fat_grams": 97
        },
        {
            "name": "Bio Kaffee Klassik",
            "calories_per_serving": 328,
            "protein_grams": 72,
            "carbohydrates_grams": 85,
            "fat_grams": 84
        },
        {
            "name": "Activia noix de coco",
            "calories_per_serving": 364,
            "protein_grams": 78,
            "carbohydrates_grams": 88,
            "fat_grams": 91
        },
        {
            "name": "Rolled Oats",
            "calories_per_serving": 585,
            "protein_grams": 97,
            "carbohydrates_grams": 81,
            "fat_grams": 86
        },
        {
            "name": "BIRELL",
            "calories_per_serving": 58,
            "protein_grams": 50,
            "carbohydrates_grams": 35,
            "fat_grams": 74
        },
        {
            "name": "Granola V\u2019nilla Almond",
            "calories_per_serving": 289,
            "protein_grams": 70,
            "carbohydrates_grams": 65,
            "fat_grams": 98
        },
        {
            "name": "Gaufres C\u00f4te d\u2019Or",
            "calories_per_serving": 220,
            "protein_grams": 19,
            "carbohydrates_grams": 4,
            "fat_grams": 65
        },
        {
            "name": "Felix",
            "calories_per_serving": 429,
            "protein_grams": 23,
            "carbohydrates_grams": 91,
            "fat_grams": 98
        },
        {
            "name": "Thin Sliced Organic Bread 21 Whole Grains and Seeds",
            "calories_per_serving": 306,
            "protein_grams": 75,
            "carbohydrates_grams": 6,
            "fat_grams": 3
        },
        {
            "name": "Goldfish flavor blasted xtra cheddar",
            "calories_per_serving": 346,
            "protein_grams": 23,
            "carbohydrates_grams": 58,
            "fat_grams": 15
        },
        {
            "name": "Puffs sweet & crunchy corn puffs",
            "calories_per_serving": 553,
            "protein_grams": 12,
            "carbohydrates_grams": 5,
            "fat_grams": 65
        },
        {
            "name": "Peanut butter puffs",
            "calories_per_serving": 334,
            "protein_grams": 28,
            "carbohydrates_grams": 63,
            "fat_grams": 99
        },
        {
            "name": "Cheerios multi-grain cereal",
            "calories_per_serving": 487,
            "protein_grams": 45,
            "carbohydrates_grams": 70,
            "fat_grams": 95
        },
        {
            "name": "Nature Valley Oats 'n Honey Granola Crunch",
            "calories_per_serving": 64,
            "protein_grams": 66,
            "carbohydrates_grams": 91,
            "fat_grams": 91
        },
        {
            "name": "Nature Valley Oats 'n Honey Protein Granola",
            "calories_per_serving": 346,
            "protein_grams": 55,
            "carbohydrates_grams": 16,
            "fat_grams": 79
        },
        {
            "name": "Nature Valley Protein Peanut Butter Dark Chocolate Chewy Bar",
            "calories_per_serving": 412,
            "protein_grams": 9,
            "carbohydrates_grams": 42,
            "fat_grams": 85
        },
        {
            "name": "Medium salsa",
            "calories_per_serving": 419,
            "protein_grams": 33,
            "carbohydrates_grams": 93,
            "fat_grams": 14
        },
        {
            "name": "kettle cooked potato chips, original",
            "calories_per_serving": 264,
            "protein_grams": 40,
            "carbohydrates_grams": 59,
            "fat_grams": 90
        },
        {
            "name": "Pineapple Chunks",
            "calories_per_serving": 356,
            "protein_grams": 65,
            "carbohydrates_grams": 28,
            "fat_grams": 74
        },
        {
            "name": "Ananasscheiben",
            "calories_per_serving": 205,
            "protein_grams": 29,
            "carbohydrates_grams": 91,
            "fat_grams": 58
        },
        {
            "name": "Cheetos Crunchy",
            "calories_per_serving": 95,
            "protein_grams": 78,
            "carbohydrates_grams": 44,
            "fat_grams": 40
        },
        {
            "name": "Lollipops",
            "calories_per_serving": 286,
            "protein_grams": 16,
            "carbohydrates_grams": 5,
            "fat_grams": 32
        },
        {
            "name": "Pure Baking Soda",
            "calories_per_serving": 582,
            "protein_grams": 15,
            "carbohydrates_grams": 45,
            "fat_grams": 97
        },
        {
            "name": "Reduced fat creamy peanut butter spread",
            "calories_per_serving": 335,
            "protein_grams": 45,
            "carbohydrates_grams": 70,
            "fat_grams": 96
        },
        {
            "name": "Pringles Original",
            "calories_per_serving": 338,
            "protein_grams": 83,
            "carbohydrates_grams": 93,
            "fat_grams": 22
        },
        {
            "name": "Pure butter",
            "calories_per_serving": 339,
            "protein_grams": 28,
            "carbohydrates_grams": 46,
            "fat_grams": 65
        },
        {
            "name": "Chocolate candies",
            "calories_per_serving": 380,
            "protein_grams": 26,
            "carbohydrates_grams": 11,
            "fat_grams": 6
        },
        {
            "name": "Mms peanut butter family size",
            "calories_per_serving": 265,
            "protein_grams": 21,
            "carbohydrates_grams": 72,
            "fat_grams": 37
        },
        {
            "name": "Mm's peanut butter",
            "calories_per_serving": 402,
            "protein_grams": 51,
            "carbohydrates_grams": 8,
            "fat_grams": 21
        },
        {
            "name": "Nut and Rice Cracker Snacks, Cheddar Cheese",
            "calories_per_serving": 576,
            "protein_grams": 87,
            "carbohydrates_grams": 73,
            "fat_grams": 66
        },
        {
            "name": "Old times orange marmalade",
            "calories_per_serving": 167,
            "protein_grams": 76,
            "carbohydrates_grams": 53,
            "fat_grams": 88
        },
        {
            "name": "Original saltine crackers",
            "calories_per_serving": 201,
            "protein_grams": 98,
            "carbohydrates_grams": 88,
            "fat_grams": 33
        },
        {
            "name": "Triscuit Original",
            "calories_per_serving": 138,
            "protein_grams": 37,
            "carbohydrates_grams": 88,
            "fat_grams": 80
        },
        {
            "name": "Chicken bouillon cubes",
            "calories_per_serving": 445,
            "protein_grams": 44,
            "carbohydrates_grams": 33,
            "fat_grams": 92
        },
        {
            "name": "Thomas original english muffins",
            "calories_per_serving": 237,
            "protein_grams": 82,
            "carbohydrates_grams": 34,
            "fat_grams": 44
        },
        {
            "name": "Fanta Berry",
            "calories_per_serving": 461,
            "protein_grams": 48,
            "carbohydrates_grams": 37,
            "fat_grams": 74
        },
        {
            "name": "Sea Salt",
            "calories_per_serving": 529,
            "protein_grams": 49,
            "carbohydrates_grams": 16,
            "fat_grams": 3
        },
        {
            "name": "Prego Traditional 680g",
            "calories_per_serving": 257,
            "protein_grams": 76,
            "carbohydrates_grams": 14,
            "fat_grams": 34
        },
        {
            "name": "Extra Crunchy Peanut Butter",
            "calories_per_serving": 102,
            "protein_grams": 8,
            "carbohydrates_grams": 99,
            "fat_grams": 82
        },
        {
            "name": "Nature s path heritage flakes whole grains cereal",
            "calories_per_serving": 549,
            "protein_grams": 85,
            "carbohydrates_grams": 45,
            "fat_grams": 90
        },
        {
            "name": "Artesano golden wheat bakery bread",
            "calories_per_serving": 432,
            "protein_grams": 47,
            "carbohydrates_grams": 24,
            "fat_grams": 58
        },
        {
            "name": "Aminos liquid all purpose seasoning",
            "calories_per_serving": 301,
            "protein_grams": 69,
            "carbohydrates_grams": 62,
            "fat_grams": 82
        },
        {
            "name": "Arborio",
            "calories_per_serving": 580,
            "protein_grams": 21,
            "carbohydrates_grams": 11,
            "fat_grams": 58
        },
        {
            "name": "Creamy Peanut Butter",
            "calories_per_serving": 491,
            "protein_grams": 27,
            "carbohydrates_grams": 37,
            "fat_grams": 57
        },
        {
            "name": "Gluten free pasta",
            "calories_per_serving": 569,
            "protein_grams": 15,
            "carbohydrates_grams": 49,
            "fat_grams": 42
        },
        {
            "name": "Purified Water",
            "calories_per_serving": 102,
            "protein_grams": 63,
            "carbohydrates_grams": 57,
            "fat_grams": 27
        },
        {
            "name": "Panda Oyster sauce 255g",
            "calories_per_serving": 564,
            "protein_grams": 35,
            "carbohydrates_grams": 80,
            "fat_grams": 13
        },
        {
            "name": "Bread",
            "calories_per_serving": 387,
            "protein_grams": 11,
            "carbohydrates_grams": 94,
            "fat_grams": 47
        },
        {
            "name": "Marmalade",
            "calories_per_serving": 545,
            "protein_grams": 94,
            "carbohydrates_grams": 29,
            "fat_grams": 10
        },
        {
            "name": "Consomme & Recipe Mix For Chicken Dishes",
            "calories_per_serving": 116,
            "protein_grams": 72,
            "carbohydrates_grams": 85,
            "fat_grams": 82
        },
        {
            "name": "Instant noodles migoreng satay flavour",
            "calories_per_serving": 491,
            "protein_grams": 88,
            "carbohydrates_grams": 46,
            "fat_grams": 11
        },
        {
            "name": "Tomato ketchup, tomato",
            "calories_per_serving": 125,
            "protein_grams": 45,
            "carbohydrates_grams": 85,
            "fat_grams": 88
        },
        {
            "name": "Hershey Cookies 'n' creme standard",
            "calories_per_serving": 198,
            "protein_grams": 31,
            "carbohydrates_grams": 95,
            "fat_grams": 99
        },
        {
            "name": "Hershey's Chocolate Syrup",
            "calories_per_serving": 128,
            "protein_grams": 10,
            "carbohydrates_grams": 94,
            "fat_grams": 22
        },
        {
            "name": "Pringles",
            "calories_per_serving": 210,
            "protein_grams": 25,
            "carbohydrates_grams": 49,
            "fat_grams": 79
        },
        {
            "name": "Peanut Butter",
            "calories_per_serving": 231,
            "protein_grams": 84,
            "carbohydrates_grams": 92,
            "fat_grams": 64
        },
        {
            "name": "Kind, breakfast bars, honey oat",
            "calories_per_serving": 293,
            "protein_grams": 77,
            "carbohydrates_grams": 26,
            "fat_grams": 42
        },
        {
            "name": "Original Oat Beverage",
            "calories_per_serving": 298,
            "protein_grams": 80,
            "carbohydrates_grams": 72,
            "fat_grams": 42
        },
        {
            "name": "Total 5% milkfat greek strained yogurt",
            "calories_per_serving": 415,
            "protein_grams": 25,
            "carbohydrates_grams": 62,
            "fat_grams": 28
        },
        {
            "name": "Lu pim's cookies orange 1x5.290 oz",
            "calories_per_serving": 464,
            "protein_grams": 77,
            "carbohydrates_grams": 91,
            "fat_grams": 60
        },
        {
            "name": "Ginger Crystallized In Dark Chocolate",
            "calories_per_serving": 142,
            "protein_grams": 33,
            "carbohydrates_grams": 64,
            "fat_grams": 9
        },
        {
            "name": "Organic Aussie Bites",
            "calories_per_serving": 372,
            "protein_grams": 45,
            "carbohydrates_grams": 79,
            "fat_grams": 10
        },
        {
            "name": "Original bbq sauce",
            "calories_per_serving": 59,
            "protein_grams": 51,
            "carbohydrates_grams": 81,
            "fat_grams": 85
        },
        {
            "name": "100% Pure U.S. Honey",
            "calories_per_serving": 112,
            "protein_grams": 80,
            "carbohydrates_grams": 61,
            "fat_grams": 15
        },
        {
            "name": "Milk vitamin d whole",
            "calories_per_serving": 221,
            "protein_grams": 70,
            "carbohydrates_grams": 74,
            "fat_grams": 63
        },
        {
            "name": "marinara sauce",
            "calories_per_serving": 433,
            "protein_grams": 7,
            "carbohydrates_grams": 4,
            "fat_grams": 97
        },
        {
            "name": "Vapor distilled water",
            "calories_per_serving": 355,
            "protein_grams": 66,
            "carbohydrates_grams": 9,
            "fat_grams": 23
        },
        {
            "name": "Bar Cookies & Cream",
            "calories_per_serving": 126,
            "protein_grams": 34,
            "carbohydrates_grams": 54,
            "fat_grams": 19
        },
        {
            "name": "Nerds, tiny tangy crunchy candy, seriously strawberry, gotta-have grape",
            "calories_per_serving": 303,
            "protein_grams": 93,
            "carbohydrates_grams": 79,
            "fat_grams": 79
        },
        {
            "name": "Powdered Peanut Butter",
            "calories_per_serving": 67,
            "protein_grams": 43,
            "carbohydrates_grams": 86,
            "fat_grams": 87
        },
        {
            "name": "Pineapple peach master brew kombucha",
            "calories_per_serving": 435,
            "protein_grams": 36,
            "carbohydrates_grams": 16,
            "fat_grams": 100
        },
        {
            "name": "Royal hawaiian orchards, sea salt & cracked pepper macadamias",
            "calories_per_serving": 203,
            "protein_grams": 84,
            "carbohydrates_grams": 74,
            "fat_grams": 89
        },
        {
            "name": "Bumblebee Bee Chunk Light Tuna In Water",
            "calories_per_serving": 200,
            "protein_grams": 64,
            "carbohydrates_grams": 55,
            "fat_grams": 46
        },
        {
            "name": "Oreo O's Cereal",
            "calories_per_serving": 520,
            "protein_grams": 52,
            "carbohydrates_grams": 26,
            "fat_grams": 100
        },
        {
            "name": "Plain Nonfat Greek Yogurt",
            "calories_per_serving": 580,
            "protein_grams": 81,
            "carbohydrates_grams": 57,
            "fat_grams": 14
        },
        {
            "name": "Balsamic vinegar of modena",
            "calories_per_serving": 481,
            "protein_grams": 21,
            "carbohydrates_grams": 94,
            "fat_grams": 86
        },
        {
            "name": "Chimichurri Cauliflower Steaks",
            "calories_per_serving": 90,
            "protein_grams": 61,
            "carbohydrates_grams": 70,
            "fat_grams": 29
        },
        {
            "name": "Panettone",
            "calories_per_serving": 259,
            "protein_grams": 45,
            "carbohydrates_grams": 19,
            "fat_grams": 81
        },
        {
            "name": "Delinut Light",
            "calories_per_serving": 414,
            "protein_grams": 60,
            "carbohydrates_grams": 24,
            "fat_grams": 21
        }
]


def add_food_data(apps, schema_editor):
    food_class = apps.get_model('calorie_counter', 'Food')
    for food in FOODS:
        try:
            duplicate_object = food_class.objects.get(
                name=food['name']
            )
            print('Duplicate food entry not added to food table:', food['name'])
        except ObjectDoesNotExist:
            food_object = food_class.objects.create(
                name=food['name'],
                calories_per_serving=food['calories_per_serving'],
                protein_grams=food['protein_grams'],
                carbohydrates_grams=food['carbohydrates_grams'],
                fat_grams=food['fat_grams']
            )


def remove_food_data(apps, schema_editor):
    food_class = apps.get_model('calorie_counter', 'Food')
    for food in FOODS:
        try:
            food_object = food_class.objects.get(
                name=food['name']
            )
            food_object.delete()
        except ObjectDoesNotExist:
            print('Food entry not found in food table:', food['name'])




class Migration(migrations.Migration):

    dependencies = [
        ("calorie_counter", "0003_load_member_test_data"),
    ]

    operations = [
        migrations.RunPython(
            add_food_data,
            remove_food_data
        )
    ]
