# Generated by Django 4.1 on 2023-07-26 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calorie_counter", "0007_alter_member_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caloriegoal",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="caloriegoals",
                to="calorie_counter.member",
            ),
        ),
        migrations.AlterField(
            model_name="dailymacrogoal",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dailymacrogoals",
                to="calorie_counter.member",
            ),
        ),
        migrations.AlterField(
            model_name="exerciselog",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exerciselogs",
                to="calorie_counter.exercise",
            ),
        ),
        migrations.AlterField(
            model_name="exerciselog",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exerciselogs",
                to="calorie_counter.member",
            ),
        ),
        migrations.AlterField(
            model_name="mealfood",
            name="food",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mealfoods",
                to="calorie_counter.food",
            ),
        ),
        migrations.AlterField(
            model_name="mealfood",
            name="meal_log",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mealfoods",
                to="calorie_counter.meallog",
            ),
        ),
        migrations.AlterField(
            model_name="meallog",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="meallogs",
                to="calorie_counter.member",
            ),
        ),
    ]
