# Generated by Django 4.1 on 2023-07-26 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "calorie_counter",
            "0008_alter_caloriegoal_member_alter_dailymacrogoal_member_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={"ordering": ["first_name", "last_name", "disambiguator"]},
        ),
    ]
