# Generated by Django 4.1 on 2023-07-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calorie_counter", "0009_alter_member_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={"ordering": ["last_name", "first_name", "disambiguator"]},
        ),
        migrations.RemoveConstraint(model_name="member", name="unique_member",),
        migrations.AddConstraint(
            model_name="member",
            constraint=models.UniqueConstraint(
                fields=("last_name", "first_name", "e_mail"), name="unique_member"
            ),
        ),
    ]
